'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {supabase} from '@/lib/supabase';
import PostLibrary from './post-library';
import AdminPanel from './admin-panel';
import {HistoryPage,ActivityPage,MissionControlPage} from './tracker-pages-v2';
import {FullSettings,settingsDefaults} from './full-settings';
import {monthlyReward} from '@/lib/reward';
import './globals.css';import './post-library.css';import './tracker-sections.css';import './video-reference.css';
const TABS=['Painel','Missões','Registros','História','Configurações','Admin'];
const blank={post_url:'',title:'Publicação do X',views:0,likes:0,reposts:0,comments:0,mission_profile_id:'',image_urls:'',video_url:''};
export default function Dashboard({session}:{session:any}){const uid=session.user.id;const[tab,setTab]=useState('Painel');const[posts,setPosts]=useState<any[]>([]);const[settings,setSettings]=useState<any>(settingsDefaults);const[profiles,setProfiles]=useState<any[]>([]);const[addOpen,setAddOpen]=useState(false);const[step,setStep]=useState<'entry'|'review'>('entry');const[form,setForm]=useState<any>(blank);const[view,setView]=useState<'list'|'cards'>('list');const[busy,setBusy]=useState(false);const[refreshing,setRefreshing]=useState(false);
const load=useCallback(async(pulse=false)=>{if(pulse)setRefreshing(true);const[{data:p},{data:s},{data:m}]=await Promise.all([supabase.from('posts').select('*').eq('user_id',uid).order('created_at',{ascending:false}),supabase.from('user_settings').select('*').eq('user_id',uid).maybeSingle(),supabase.from('mission_profiles').select('*').eq('user_id',uid).eq('active',true).order('name')]);setPosts(p||[]);setSettings({...settingsDefaults,...(s||{})});setProfiles(m||[]);if(pulse)setTimeout(()=>setRefreshing(false),700)},[uid]);useEffect(()=>{load()},[load]);
const reward=useMemo(()=>monthlyReward(posts,!!settings.cap_unlocked),[posts,settings.cap_unlocked]);const reposts=posts.reduce((a,p)=>a+Number(p.reposts||0),0),comments=posts.reduce((a,p)=>a+Number(p.comments||0),0),engagement=reward.views?((reward.likes+reposts+comments)/reward.views)*100:0;
async function addPost(){if(!form.post_url.trim())return;setBusy(true);const mp=profiles.find(x=>String(x.id)===String(form.mission_profile_id));const imgs=String(form.image_urls||'').split(/[\n,]/).map((x:string)=>x.trim()).filter(Boolean);await supabase.from('posts').insert({user_id:uid,title:form.title.trim()||'Publicação do X',post_url:form.post_url.trim(),views:Number(form.views),likes:Number(form.likes),reposts:Number(form.reposts),comments:Number(form.comments),mission_profile_id:mp?.id||null,mission_name:mp?.name||null,special_reward:Number(mp?.reward||0),network:'X',image_urls:imgs,video_url:form.video_url||null,author_handle:settings.x_handle||null,metrics_source:'manual',metrics_updated_at:new Date().toISOString()});setBusy(false);setAddOpen(false);setStep('entry');setForm(blank);await load(true)}
async function closeMonth(){if(!confirm('Fechar o período atual?'))return;const d=new Date(),month=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`;await supabase.from('archived_periods').insert({user_id:uid,month,summary:{total:reward.total,posts:posts.length,views:reward.views,likes:reward.likes,reposts,comments,base:reward.base,viewsReward:reward.viewsReward,engagementReward:reward.engagementReward,special:reward.special},posts_snapshot:posts});setTab('História')}
return <div className="tracker-app"><header className="tracker-top"><div className="tracker-brand">RASTREADOR DE CRISTAIS</div><nav>{TABS.slice(0,5).map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x.toUpperCase()}</button>)}</nav><div className="top-actions"><button className={refreshing?'refreshing':''} onClick={()=>load(true)}>{refreshing?'ATUALIZANDO...':'ATUALIZAR'}</button><button className="tracker-add" onClick={()=>{setStep('entry');setAddOpen(true)}}>+ NOVA PUBLICAÇÃO</button></div></header><main className="tracker-content">
{tab==='Painel'&&<><div className="notice-video">Dados armazenados localmente na sua conta. Use “Atualizar” para sincronizar as métricas exibidas.</div><section className="tracker-hero"><div><small>VISÃO GERAL</small><h1>PAINEL</h1></div><div className="tracker-period">PERÍODO ATUAL</div></section>{posts.length?<><section className="tracker-stats"><Stat label="PUBLICAÇÕES" value={posts.length}/><Stat label="VISUALIZAÇÕES" value={reward.views}/><Stat label="CURTIDAS" value={reward.likes}/><Stat label="CRYSTALGIN" value={reward.total}/></section><section className="tracker-panel"><div className="tracker-panel-head"><div><h2>MINHAS PUBLICAÇÕES</h2><p>Acompanhe a prévia, métricas e o cálculo de cada postagem.</p></div><div className="view-switch"><button className={view==='list'?'active':''} onClick={()=>setView('list')}>LISTA</button><button className={view==='cards'?'active':''} onClick={()=>setView('cards')}>CARTÕES</button></div></div><div className={`post-view ${view}`}><PostLibrary userId={uid} posts={posts} reload={load}/></div></section><MonthlyReport reward={reward} reposts={reposts} comments={comments} engagement={engagement} closeMonth={closeMonth}/></>:<section className="tracker-empty video-empty"><div className="empty-line"/><h3>SEU DASHBOARD ESTÁ VAZIO</h3><p>Clique no botão abaixo para adicionar sua primeira publicação e começar a rastrear engajamento e recompensa.</p><button className="tracker-add" onClick={()=>setAddOpen(true)}>+ ADICIONAR PUBLICAÇÃO</button></section>}</>}
{tab==='Missões'&&<MissionControlPage uid={uid} reloadProfiles={load}/>} {tab==='Registros'&&<ActivityPage uid={uid}/>} {tab==='História'&&<HistoryPage uid={uid}/>} {tab==='Configurações'&&<FullSettings uid={uid} settings={settings} setSettings={setSettings}/>} {tab==='Admin'&&<AdminPanel currentUserId={uid}/>}</main>
{addOpen&&<div className="modal-backdrop dark"><div className="tracker-modal video-modal"><div className="modal-head"><div><small>{step==='entry'?'NOVA PUBLICAÇÃO':'REVISÃO'}</small><strong>{step==='entry'?'Enviar nova publicação':'Revisar publicação'}</strong></div><button onClick={()=>setAddOpen(false)}>×</button></div><div className="modal-body">{step==='entry'?<><label>Link da publicação<input placeholder="https://x.com/.../status/..." value={form.post_url} onChange={e=>setForm({...form,post_url:e.target.value})}/></label><label>Título / identificação<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Missão<select value={form.mission_profile_id} onChange={e=>setForm({...form,mission_profile_id:e.target.value})}><option value="">Sem missão especial</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="metric-input-grid"><Num k="views" label="Visualizações"/><Num k="likes" label="Curtidas"/><Num k="reposts" label="Reposts"/><Num k="comments" label="Comentários"/></div><label>Imagens (URLs, uma por linha)<textarea rows={3} value={form.image_urls} onChange={e=>setForm({...form,image_urls:e.target.value})}/></label><label>URL direta do vídeo<input value={form.video_url} onChange={e=>setForm({...form,video_url:e.target.value})}/></label><div className="bonus-locks"><label><input type="checkbox" disabled/> Imagem excepcional</label><label><input type="checkbox" disabled/> Bônus de Repostagem</label></div></>:<Review form={form} handle={settings.x_handle}/>}</div><div className="modal-actions"><button className="btn" onClick={()=>step==='review'?setStep('entry'):setAddOpen(false)}>{step==='review'?'VOLTAR':'CANCELAR'}</button>{step==='entry'?<button className="tracker-add" disabled={!form.post_url.trim()} onClick={()=>setStep('review')}>REVISAR PUBLICAÇÃO</button>:<button className="tracker-add" disabled={busy} onClick={addPost}>{busy?'ENVIANDO...':'ENVIAR PUBLICAÇÃO'}</button>}</div></div></div>}</div>
function Num({k,label}:{k:string,label:string}){return <label>{label}<input type="number" min="0" value={form[k]} onChange={e=>setForm({...form,[k]:Number(e.target.value)})}/></label>}}
function Stat({label,value}:{label:string,value:number}){return <div className="tracker-stat"><small>{label}</small><strong>{Number(value).toLocaleString('pt-BR')}</strong><span>ATUALIZADO</span></div>}
function Review({form,handle}:{form:any,handle:string}){const imgs=String(form.image_urls||'').split(/[\n,]/).map((x:string)=>x.trim()).filter(Boolean);return <div className="review-card"><div className="review-user"><span>{(handle||'X').slice(0,1).toUpperCase()}</span><div><b>{handle?'@'+handle:'Publicação do X'}</b><small>{form.post_url}</small></div></div><h3>{form.title}</h3>{imgs.length>0&&<div className={`media-grid n${Math.min(imgs.length,4)}`}>{imgs.slice(0,4).map((x:string,i:number)=><img key={i} src={x} alt="Prévia"/>)}</div>}{form.video_url&&<video src={form.video_url} controls muted playsInline/>}<div className="review-metrics"><span>◉ {Number(form.views).toLocaleString('pt-BR')}</span><span>♡ {Number(form.likes).toLocaleString('pt-BR')}</span><span>↻ {Number(form.reposts).toLocaleString('pt-BR')}</span><span>◌ {Number(form.comments).toLocaleString('pt-BR')}</span></div></div>}
function MonthlyReport({reward,reposts,comments,engagement,closeMonth}:{reward:any,reposts:number,comments:number,engagement:number,closeMonth:()=>void}){return <section className="tracker-report detailed"><div className="report-head"><div><small>RELATÓRIO</small><h2>RESUMO MENSAL</h2></div><strong>◆ {reward.total.toLocaleString('pt-BR')} CG</strong></div><div className="tracker-stat-row"><Mini label="Engajamento" value={`${engagement.toFixed(2)}%`}/><Mini label="Repostagens" value={reposts}/><Mini label="Comentários" value={comments}/><Mini label="Curtidas" value={reward.likes}/></div><div className="calc-log"><h3>DETALHAMENTO DO CÁLCULO</h3><p><span>Recompensa básica</span><b>{reward.base.toLocaleString('pt-BR')}</b></p><p><span>Faixa de visualizações</span><b>{reward.viewsReward.toLocaleString('pt-BR')}</b></p><p><span>Curtidas × 2</span><b>{reward.engagementReward.toLocaleString('pt-BR')}</b></p><p><span>Missões especiais</span><b>{reward.special.toLocaleString('pt-BR')}</b></p><p className="total"><span>CRYSTALGIN TOTAL</span><b>{reward.total.toLocaleString('pt-BR')}</b></p></div><button className="danger-wide" onClick={closeMonth}>FECHAR MÊS</button></section>}
function Mini({label,value}:{label:string,value:any}){return <div><small>{label}</small><strong>{typeof value==='number'?value.toLocaleString('pt-BR'):value}</strong></div>}
