"use client";
import {type CSSProperties,useEffect,useState} from "react";
import {supabase} from "@/lib/supabase";
import type {MissionPost} from "./missions";
import {ReferencePanel} from "./reference-panel";
import {MissionControlV2} from "./mission-control-v2";
import {RankingSection,HistorySection,ActivitySection,FullSettings} from "./tracker-sections";
import {AddPublicationModal} from "./add-publication-modal";
type User={name:string;email:string}|null;
type Settings={refresh_interval:number;show_refresh_timer:boolean;app_name:string;accent_color:string;background_color:string;surface_color:string;border_color:string};
const descriptions:Record<string,string>={Painel:"Acompanhe o crescimento e descubra o que mais engaja sua comunidade.",Classificação:"Compare seu desempenho mensal e acompanhe sua posição no ranking.",História:"Consulte e gerencie os períodos mensais que você arquivou.","Centro de Controle da Missão":"Controle recompensas, limites mensais e missões especiais.","Registro de atividades":"Acompanhe alterações e notificações importantes.",Configurações:"Personalize o rastreador e suas preferências."};
function clock(total:number){const h=Math.floor(total/3600),m=Math.floor(total%3600/60),s=total%60;return [h,m,s].map(v=>String(v).padStart(2,"0")).join(":")}
export default function Dashboard({user}:{user:User}){const today=new Date().toISOString().slice(0,10),[tab,setTab]=useState("Painel"),[posts,setPosts]=useState<MissionPost[]>([]),[showAdd,setShowAdd]=useState(false),[notice,setNotice]=useState(""),[rangeStart,setRangeStart]=useState(`${today.slice(0,7)}-01`),[rangeEnd,setRangeEnd]=useState(today),[seconds,setSeconds]=useState(0),[settings,setSettings]=useState<Settings>({refresh_interval:0,show_refresh_timer:true,app_name:"VENENO",accent_color:"#f6ad55",background_color:"#121212",surface_color:"#1e1e1e",border_color:"#2c2c2c"});const pref=`anonymous-oh-appearance:${user?.email||"guest"}`,tabKey=`anonymous-oh-active-tab:${user?.email||"guest"}`;
useEffect(()=>{const saved=localStorage.getItem(tabKey);if(saved&&descriptions[saved])setTab(saved)},[tabKey]);
useEffect(()=>{supabase.from("posts").select("id,title,published_at,views,likes,comments,reposts,bookmarks,created_at,network,mission_profile_id,mission_name,special_reward,exceptional_image,repost_bonus,post_url,external_post_id,metrics_source,metrics_updated_at,image_urls,video_url,author_name,author_handle,author_avatar,admin_eligible,admin_reason").order("published_at",{ascending:false}).then(({data,error})=>{if(error)return;setPosts((data||[]).map((p:any)=>({id:p.id,title:p.title,publishedAt:p.published_at,views:Number(p.views||0),likes:Number(p.likes||0),comments:Number(p.comments||0),reposts:Number(p.reposts||0),bookmarks:Number(p.bookmarks||0),createdAt:p.created_at,network:p.network||"X",missionProfileId:p.mission_profile_id,missionName:p.mission_name,specialReward:Number(p.special_reward||0),exceptionalImage:!!p.exceptional_image,repostBonus:!!p.repost_bonus,postUrl:p.post_url,externalPostId:p.external_post_id,metricsSource:p.metrics_source,metricsUpdatedAt:p.metrics_updated_at,imageUrls:p.image_urls||[],videoUrl:p.video_url||null,authorName:p.author_name,authorHandle:p.author_handle,authorAvatar:p.author_avatar,adminEligible:p.admin_eligible!==false,adminReason:p.admin_reason})))})},[]);
useEffect(()=>{supabase.from("user_settings").select("refresh_interval,show_refresh_timer,app_name,accent_color,background_color,surface_color,border_color").maybeSingle().then(({data})=>{if(data)setSettings(current=>({...current,...data,app_name:data.app_name&&data.app_name!=="ANONIMOUS_OH Analytics"?data.app_name:"VENENO"}))});const changed=(event:Event)=>setSettings(current=>({...current,...((event as CustomEvent).detail||{})}));window.addEventListener("user-settings-updated",changed);return()=>window.removeEventListener("user-settings-updated",changed)},[]);
useEffect(()=>{const hours=Number(settings.refresh_interval)||0;if(!hours){setSeconds(0);return}const key=`anonymous-oh-next-refresh:${user?.email||"guest"}`,duration=hours*3600000;let next=Number(localStorage.getItem(key));if(!next||next<=Date.now())next=Date.now()+duration;localStorage.setItem(key,String(next));const tick=()=>{const left=Math.max(0,Math.ceil((next-Date.now())/1000));setSeconds(left);if(left===0){next=Date.now()+duration;localStorage.setItem(key,String(next));window.dispatchEvent(new Event("refresh-x-posts"))}};tick();const id=window.setInterval(tick,1000);return()=>window.clearInterval(id)},[settings.refresh_interval,user?.email]);
function go(next:string){setTab(next);localStorage.setItem(tabKey,next)}const nav=["Painel","Classificação","História","Centro de Controle da Missão","Registro de atividades","Configurações"];return <div className="app-shell ui-comfortable" style={{"--green":settings.accent_color,"--bg":settings.background_color,"--panel":settings.surface_color,"--panel2":settings.surface_color,"--line":settings.border_color,"--theme-surface":settings.surface_color,"--theme-border":settings.border_color,"--theme-background":settings.background_color} as CSSProperties}><aside className="sidebar"><div className="brand"><b>CENTRAL DE<br/>PERFORMANCE</b></div>{settings.show_refresh_timer&&settings.refresh_interval>0&&<span className="refresh-timer">{clock(seconds)}</span>}<nav>{nav.map(name=><button className={tab===name?"active":""} onClick={()=>go(name)} key={name}><span>{name}</span></button>)}</nav><div className="side-bottom"><div className="profile"><div className="avatar">A</div><div><b>{settings.app_name||"VENENO"}</b></div></div></div></aside><main className="content">{tab!=="Painel"&&<header><div><p className="eyebrow">CENTRAL DE PERFORMANCE</p><h1>{tab}</h1><p>{descriptions[tab]}</p></div><div className="header-actions"><button className="signout" onClick={()=>supabase.auth.signOut()}>Sair</button><button className="primary" onClick={()=>setShowAdd(true)}>＋ Nova publicação</button></div></header>}{notice&&<div className="notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}{tab==="Painel"&&<ReferencePanel posts={posts} setPosts={setPosts} add={()=>setShowAdd(true)} bulk={()=>setShowAdd(true)} report={()=>window.print()} notify={setNotice} preferenceKey={pref} rangeStart={rangeStart} rangeEnd={rangeEnd} setRangeStart={setRangeStart} setRangeEnd={setRangeEnd} missions={()=>go("Centro de Controle da Missão")}/>} {tab==="Classificação"&&<RankingSection posts={posts}/>} {tab==="História"&&<HistorySection/>} {tab==="Centro de Controle da Missão"&&<MissionControlV2/>} {tab==="Registro de atividades"&&<ActivitySection/>} {tab==="Configurações"&&<FullSettings userEmail={user?.email}/>}<footer><span>ANONIMOUS_OH Analytics V2</span><span>Feito para criadores de Once Human • Dados protegidos</span></footer></main>{showAdd&&<AddPublicationModal close={()=>setShowAdd(false)} notify={setNotice} onCreated={post=>setPosts(current=>[post,...current])}/>}</div>}
