'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {supabase} from '@/lib/supabase';
import PostLibrary from './post-library';
import AdminPanel from './admin-panel';
import {HistoryPage,ActivityPage,MissionControlPage,RankingPage} from './tracker-pages-v2';
import {FullSettings,settingsDefaults} from './full-settings';
import {monthlyReward} from '@/lib/reward';
import ReportPage from './report-page';
import './globals.css';import './post-library.css';import './tracker-sections.css';import './video-reference.css';import './screenshot-exact.css';import './interactions.css';import './add-publication.css';

const blank={post_url:'',title:'PublicaÃ§Ã£o do X',views:0,likes:0,reposts:0,comments:0,mission_profile_id:'',image_urls:'',video_url:'',published_date:''};
const nav=['Painel','ClassificaÃ§Ã£o','HistÃ³ria','Centro de Controle da MissÃ£o','Registro de atividades','ConfiguraÃ§Ãµes'];
type Deltas={posts:number;views:number;involvement:number;crystal:number};

export default function Dashboard({session}:{session:any}){
 const uid=session.user.id;
 const[tab,setTab]=useState(()=>typeof window!=='undefined'?(localStorage.getItem('aoh:last-tab')||'Painel'):'Painel');const[posts,setPosts]=useState<any[]>([]);const[settings,setSettings]=useState<any>(settingsDefaults);const[profiles,setProfiles]=useState<any[]>([]);const[reportOpen,setReportOpen]=useState(false);const[addOpen,setAddOpen]=useState(false);const[bulkOpen,setBulkOpen]=useState(false);const[bulkMission,setBulkMission]=useState('');const[bulkText,setBulkText]=useState('');const[bulkMsg,setBulkMsg]=useState('');const[form,setForm]=useState<any>(blank);const[busy,setBusy]=useState(false);const[autoLoading,setAutoLoading]=useState(false);const[refreshing,setRefreshing]=useState(false);const[refreshStep,setRefreshStep]=useState(1);const[deltas,setDeltas]=useState<Deltas>({posts:0,views:0,involvement:0,crystal:0});const[showDeltas,setShowDeltas]=useState(false);const[view,setView]=useState<'list'|'cards'>(()=>typeof window!=='undefined'&&localStorage.getItem('aoh:post-view')==='cards'?'cards':'list');
 const chooseTab=(item:string)=>{setBulkOpen(false);setTab(item);if(typeof window!=='undefined')localStorage.setItem('aoh:last-tab',item)};
 const chooseView=(mode:'list'|'cards')=>{setView(mode);if(typeof window!=='undefined')localStorage.setItem('aoh:post-view',mode)};
 const openAdd=()=>{setForm({...blank,published_date:new Date().toISOString().slice(0,10)});setAddOpen(true)};
 const totalsFor=(rows:any[])=>{const views=rows.reduce((a,p)=>a+Number(p.views||0),0),likes=rows.reduce((a,p)=>a+Number(p.likes||0),0),reposts=rows.reduce((a,p)=>a+Number(p.reposts||0),0),comments=rows.reduce((a,p)=>a+Number(p.comments||0),0),special=rows.reduce((a,p)=>a+Number(p.special_reward||0),0);return{posts:rows.length,views,involvement:likes+reposts+comments,crystal:likes*2+special}};
 const load=useCallback(async(pulse=false)=>{const before=totalsFor(posts);if(pulse){setRefreshing(true);setRefreshStep(1);setShowDeltas(false)}const[{data:p},{data:s},{data:m}]=await Promise.all([supabase.from('posts').select('*').eq('user_id',uid).order('created_at',{ascending:false}),supabase.from('user_settings').select('*').eq('user_id',uid).maybeSingle(),supabase.from('mission_profiles').select('*').eq('user_id',uid).order('name')]);if(pulse)setRefreshStep(2);const next=p||[];setPosts(next);setSettings({...settingsDefaults,...(s||{})});setProfiles(m||[]);if(!bulkMission&&m?.length)setBulkMission(String(m.find((x:any)=>x.active)?.id||''));if(pulse){const after=totalsFor(next),d={posts:after.posts-before.posts,views:after.views-before.views,involvement:after.involvement-before.involvement,crystal:after.crystal-before.crystal};setDeltas(d);setRefreshing(false);if(Object.values(d).some(v=>v>0)){setShowDeltas(true);setTimeout(()=>setShowDeltas(false),6500)}}},[uid,bulkMission,posts]);
 useEffect(()=>{load()},[]);
 useEffect(()=>{const open=()=>setReportOpen(true);window.addEventListener('aoh:open-report',open);return()=>window.removeEventListener('aoh:open-report',open)},[]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'&&addOpen)setAddOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[addOpen]);
 async function fetchPostData(url:string){const r=await fetch('/api/x-metrics',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});const data=await r.json();if(!r.ok||data.error)throw new Error(data.error||'Falha na coleta');return data}
 useEffect(()=>{if(!addOpen||!/https?:\/\/(?:www\.)?(?:x\.com|twitter\.com)\/[^/]+\/status\/\d+/i.test(form.post_url||''))return;let alive=true;const timer=setTimeout(async()=>{setAutoLoading(true);try{const d=await fetchPostData(form.post_url);if(alive)setForm((f:any)=>({...f,title:d.title||f.title,views:Number(d.views||0),likes:Number(d.likes||0),reposts:Number(d.reposts||0),comments:Number(d.comments||0),published_date:d.published_date||f.published_date,image_urls:Array.isArray(d.image_urls)?d.image_urls.join('\n'):f.image_urls,video_url:d.video_url||f.video_url}))}catch{}finally{if(alive)setAutoLoading(false)}},450);return()=>{alive=false;clearTimeout(timer)}},[addOpen,form.post_url]);
 const reward=useMemo(()=>monthlyReward(posts,!!settings.cap_unlocked),[posts,settings.cap_unlocked]);
 const reposts=posts.reduce((a,p)=>a+Number(p.reposts||0),0),comments=posts.reduce((a,p)=>a+Number(p.comments||0),0),involvement=reward.likes+reposts+comments;
 const missionRows=useMemo(()=>{const map=new Map<string,{name:string,color:string,posts:number,views:number,likes:number,crystalgin:number}>();for(const p of posts){const name=p.mission_name||'SEM MISSÃƒO';const profile=profiles.find(x=>x.name===name);const r=map.get(name)||{name,color:profile?.color||'#f6ad55',posts:0,views:0,likes:0,crystalgin:0};r.posts++;r.views+=Number(p.views||0);r.likes+=Number(p.likes||0);r.crystalgin+=Number(p.special_reward||0)+Number(p.likes||0)*2;map.set(name,r)}return [...map.values()]},[posts,profiles]);
 const missionTotals=useMemo(()=>missionRows.reduce((a,r)=>({posts:a.posts+r.posts,views:a.views+r.views,likes:a.likes+r.likes,crystalgin:a.crystalgin+r.crystalgin}),{posts:0,views:0,likes:0,crystalgin:0}),[missionRows]);
 const selectedMission=profiles.find(x=>String(x.id)===String(form.mission_profile_id));
 async function addPost(){if(!form.post_url.trim())return;setBusy(true);const mp=profiles.find(x=>String(x.id)===String(form.mission_profile_id));const imgs=String(form.image_urls||'').split(/[\n,]/).map((x:string)=>x.trim()).filter(Boolean);await supabase.from('posts').insert({user_id:uid,title:form.title.trim()||'PublicaÃ§Ã£o do X',post_url:form.post_url.trim(),views:Number(form.views),likes:Number(form.likes),reposts:Number(form.reposts),comments:Number(form.comments),mission_profile_id:mp?.id||null,mission_name:mp?.name||null,special_reward:Number(mp?.reward||0),network:'X',image_urls:imgs,video_url:form.video_url||null,author_handle:settings.x_handle||null,metrics_source:'auto',metrics_updated_at:new Date().toISOString()});setBusy(false);setAddOpen(false);setForm(blank);await load(true)}
 async function processBulk(){const urls=[...new Set((bulkText.match(/https?:\/\/[^\s]+/g)||[]).map(x=>x.replace(/[),.;]+$/,'')))].filter(x=>/https?:\/\/(www\.)?(x\.com|twitter\.com)\//i.test(x));if(!urls.length){setBulkMsg('Nenhum link vÃ¡lido do X foi encontrado.');return}setBusy(true);setBulkMsg(`Coletando dados de ${urls.length} publicaÃ§Ã£o(Ãµes)...`);const mp=profiles.find(x=>String(x.id)===String(bulkMission));const rows=await Promise.all(urls.map(async url=>{let d:any={};try{d=await fetchPostData(url)}catch{}return{user_id:uid,title:d.title||'PublicaÃ§Ã£o do X',post_url:url,views:Number(d.views||0),likes:Number(d.likes||0),reposts:Number(d.reposts||0),comments:Number(d.comments||0),mission_profile_id:mp?.id||null,mission_name:mp?.name||null,special_reward:Number(mp?.reward||0),network:'X',author_handle:d.author_handle||settings.x_handle||null,image_urls:Array.isArray(d.image_urls)?d.image_urls:[],video_url:d.video_url||null,metrics_source:d.source||'auto',metrics_updated_at:new Date().toISOString()}}));const{error}=await supabase.from('posts').insert(rows);setBusy(false);if(error){setBulkMsg('NÃ£o foi possÃ­vel adicionar os links.');return}setBulkMsg(`${urls.length} publicaÃ§Ã£o(Ãµes) adicionada(s) com preenchimento automÃ¡tico.`);setBulkText('');await load(true)}
 async function closeMonth(){if(!confirm('Fechar o perÃ­odo atual?'))return;const d=new Date(),month=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`;await supabase.from('archived_periods').insert({user_id:uid,month,summary:{total:reward.total,posts:posts.length,views:reward.views,likes:reward.likes,reposts,comments,base:reward.base,viewsReward:reward.viewsReward,engagementReward:reward.engagementReward,special:reward.special},posts_snapshot:posts});chooseTab('HistÃ³ria')}
 async function signOut(){await supabase.auth.signOut()}
 const username=(settings.app_name||settings.x_handle||'VENENO').toUpperCase();
 if(reportOpen)return <ReportPage posts={posts} profiles={profiles} settings={settings} onCancel={()=>setReportOpen(false)}/>;
 return <div className="exact-app">
  <header className="exact-topbar"><div className="exact-brand">RASTREADOR DE<br/>VENON</div>{refreshing?<div className="refresh-pill"><span className="refresh-spin">â†»</span><span>ATUALIZANDO MÃ‰TRICAS<br/><b>({refreshStep}/2)</b></span></div>:<div className="wait-pill">â—&nbsp; ESPERA</div>}<nav className="exact-nav">{nav.map(item=><button key={item} className={tab===item?'active':''} onClick={()=>chooseTab(item)}><span className="nav-icon">{iconFor(item)}</span><span>{item}</span></button>)}</nav><button className="user-pill" onClick={signOut}><span>â—‰</span>{username}</button></header>
  <main className="exact-main">
   {bulkOpen?<BulkPosts profiles={profiles} bulkMission={bulkMission} setBulkMission={setBulkMission} bulkText={bulkText} setBulkText={setBulkText} busy={busy} msg={bulkMsg} process={processBulk} back={()=>setBulkOpen(false)}/>:<>
   {tab==='Painel'&&<>
    <section className="exact-hero"><div className="hero-title"><h1>PAINEL</h1><span>{posts.length}</span></div><div className="hero-actions"><button>â‡© <b>IMPORTAR</b></button><div className="split-btn"><button>JSON</button><button>CSV</button></div><button className="report-btn">â–¤ <b>RELATÃ“RIO</b></button><button onClick={()=>setBulkOpen(true)}>â–¤ <b>ADIÃ‡ÃƒO EM MASSA</b></button><button className="blue-btn" onClick={closeMonth}>â—´ <b>FECHAR MÃŠS</b></button><button className={`green-btn ${refreshing?'is-refreshing':''}`} disabled={refreshing} onClick={()=>load(true)}>â†» <b>ATUALIZAR AGORA (MANUAL)</b></button><button className="orange-add" onClick={openAdd}>ï¼‹ <b>ADICIONAR PUBLICAÃ‡ÃƒO</b></button></div></section>
    <section className="exact-stats"><ExactStat label="TOTAL DE PUBLICAÃ‡Ã•ES" value={posts.length} delta={showDeltas?deltas.posts:0}/><ExactStat label="VISUALIZAÃ‡Ã•ES TOTAIS" value={reward.views} delta={showDeltas?deltas.views:0}/><div className="exact-stat progress-stat"><div className="stat-label-row"><small>PROGRESSO DE<br/>CRISTGIN</small><span>FÃ“RMULA<br/>OFICIAL</span></div><div className="stat-value-line"><strong>{reward.total.toLocaleString('pt-BR')} <em>/ 30 000</em></strong>{showDeltas&&deltas.crystal>0&&<DeltaBadge value={deltas.crystal}/>}</div><div className="progress-line"><i style={{width:`${Math.min(100,reward.total/30000*100)}%`}}/></div></div><ExactStat label="ENVOLVIMENTO TOTAL" value={involvement} delta={showDeltas?deltas.involvement:0}/><ExactStat label="CRISTAL TOTAL" value={reward.total} accent delta={showDeltas?deltas.crystal:0}/></section>
    <section className="formula-strip"><div className="formula-label">FÃ“RMULA V2</div><div className="formula-caption">DETALHAMENTO DA RECOMPENSA OFICIAL</div><FormulaItem label="BÃSICO (MAIS DE 10 POSTS)" value={reward.base}/><FormulaItem label="VISUALIZAR (COLHEITA)" value={reward.viewsReward}/><FormulaItem label="ENGAJAMENTO (CURTIDAS X2)" value={reward.engagementReward}/><FormulaItem label="MISSÃ•ES ESPECIAIS" value={reward.special}/><FormulaItem label="TOTAL SEM CAP" value={reward.total} total/></section>
    <section className="mission-table mission-summary-card"><div className="mission-head"><h2>DESEMPENHO POR MISSÃƒO</h2><span>RESUMO POR CATEGORIA</span></div><div className="mission-row mission-columns"><b>MISSÃƒO</b><b>POSTAGENS</b><b>IMPRESSÃ•ES/VISUALIZAÃ‡Ã•ES TOTAIS</b><b>CURTIDAS</b><b>CRYSTGIN</b></div>{missionRows.map(r=><div className="mission-row" key={r.name}><div className="mission-name"><i style={{background:r.color,boxShadow:`0 0 10px ${r.color}`}}/><strong>{r.name}</strong></div><span>{r.posts}</span><span>{r.views.toLocaleString('pt-BR')}</span><span>{r.likes.toLocaleString('pt-BR')}</span><strong className="orange-text">{r.crystalgin.toLocaleString('pt-BR')}</strong></div>)}{!missionRows.length&&<div className="mission-empty">Nenhuma missÃ£o com publicaÃ§Ãµes.</div>}<div className="mission-row mission-total-row"><strong>TOTAL</strong><strong>{missionTotals.posts.toLocaleString('pt-BR')}</strong><strong>{missionTotals.views.toLocaleString('pt-BR')}</strong><strong>{missionTotals.likes.toLocaleString('pt-BR')}</strong><strong>{missionTotals.crystalgin.toLocaleString('pt-BR')}</strong></div><div className="mission-reward-summary"><div className="mission-reward-line"><span>RECOMPENSA BÃSICA <small>(MÃN. 10 POSTAGENS)</small></span><strong>+ {reward.base.toLocaleString('pt-BR')} <em>CG</em></strong></div><div className="mission-reward-line"><span>BÃ”NUS DE VISUALIZAÃ‡Ã•ES <small>(COLHETES)</small></span><strong>+ {reward.viewsReward.toLocaleString('pt-BR')} <em>CG</em></strong></div><div className="mission-official-divider"/><div className="mission-official-total"><span>TOTAL OFICIAL <small>(COM CAP)</small></span><strong>{reward.total.toLocaleString('pt-BR')} <em>CG</em></strong></div></div></section>
    {posts.length>0&&<section className="exact-posts"><div className="posts-head"><h2>PUBLICAÃ‡Ã•ES</h2><div><button className={view==='list'?'active':''} onClick={()=>chooseView('list')}>LISTA</button><button className={view==='cards'?'active':''} onClick={()=>chooseView('cards')}>CARTÃ•ES</button></div></div><div className={`post-view ${view}`}><PostLibrary userId={uid} posts={posts} reload={load}/></div></section>}
   </>}
   {tab==='ClassificaÃ§Ã£o'&&<RankingPage/>}{tab==='HistÃ³ria'&&<HistoryPage uid={uid}/>} {tab==='Centro de Controle da MissÃ£o'&&<MissionControlPage uid={uid} reloadProfiles={load}/>} {tab==='Registro de atividades'&&<ActivityPage uid={uid}/>} {tab==='ConfiguraÃ§Ãµes'&&<FullSettings uid={uid} settings={settings} setSettings={setSettings}/>} {tab==='Admin'&&<AdminPanel currentUserId={uid}/>}</>}
  </main>
  {addOpen&&<div className="add-publication-screen" onMouseDown={e=>{if(e.target===e.currentTarget)setAddOpen(false)}}><div className="add-publication-shell" onMouseDown={e=>e.stopPropagation()}><div className="add-publication-heading"><div className="add-publication-plus">ï¼‹</div><div><h2>Enviar nova publicaÃ§Ã£o</h2><p>{autoLoading?'Coletando automaticamente os dados da postagem...':'Cole o link do X e os dados serÃ£o preenchidos automaticamente.'}</p></div></div><section className="add-publication-card"><label className="add-field">URL da postagem<input autoFocus value={form.post_url} onChange={e=>setForm({...form,post_url:e.target.value})} placeholder="https://x.com/your-post"/></label><div className="add-group-label">MÃ©tricas de engajamento</div><div className="add-metrics-grid"><MetricInput icon="â—‰" value={form.views} onChange={v=>setForm({...form,views:v})}/><MetricInput icon="â—¯" value={form.comments} onChange={v=>setForm({...form,comments:v})}/><MetricInput icon="â†”" value={form.reposts} onChange={v=>setForm({...form,reposts:v})}/><MetricInput icon="â™¥" heart value={form.likes} onChange={v=>setForm({...form,likes:v})}/></div><div className="add-two-column"><label className="add-field">Data da publicaÃ§Ã£o<div className="add-input-icon"><span>â–£</span><input type="date" value={form.published_date||''} onChange={e=>setForm({...form,published_date:e.target.value})}/></div></label><label className="add-field">MissÃ£o<div className="add-mission-select"><i style={{background:selectedMission?.color||'#38d27f'}}/><select value={form.mission_profile_id} onChange={e=>setForm({...form,mission_profile_id:e.target.value})}><option value="">Sem missÃ£o especial</option>{profiles.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div></label></div><div className="add-group-label add-bonus-title">BÃ´nus</div><div className="add-bonus-row"><label className="locked-bonus"><input type="checkbox" disabled/><span/>Imagem em destaque</label><label className="locked-bonus"><input type="checkbox" disabled/><span/>BÃ´nus de ReproduÃ§Ã£o</label></div><button className="add-submit" disabled={busy||autoLoading||!form.post_url.trim()} onClick={addPost}>ï¼‹ <b>{autoLoading?'COLETANDO...':busy?'ADICIONANDO...':'Adicionar publicaÃ§Ã£o'}</b></button></section></div></div>}
 </div>
}
function MetricInput({icon,value,onChange,heart=false}:{icon:string;value:number;onChange:(v:number)=>void;heart?:boolean}){return <div className="add-metric-input"><span className={heart?'heart':''}>{icon}</span><input type="number" min="0" value={value} onChange={e=>onChange(Number(e.target.value))}/></div>}
function BulkPosts({profiles,bulkMission,setBulkMission,bulkText,setBulkText,busy,msg,process,back}:{profiles:any[];bulkMission:string;setBulkMission:(v:string)=>void;bulkText:string;setBulkText:(v:string)=>void;busy:boolean;msg:string;process:()=>void;back:()=>void}){return <section className="bulk-page" style={{maxWidth:760,margin:'16px auto'}}><div className="bulk-title"><button onClick={back}>â–¤</button><div><h1>Postagens em Massa</h1><p>Cole uma lista de URLs de postagens abaixo, uma por linha. As mÃ©tricas e mÃ­dias serÃ£o coletadas automaticamente.</p></div></div><div className="bulk-card" style={{background:'#1c1c1c',border:'1px solid #2b2b2b',borderRadius:8,padding:30}}><label>MissÃ£o PadrÃ£o para Novos Posts<select value={bulkMission} onChange={e=>setBulkMission(e.target.value)}><option value="">Sem missÃ£o especial</option>{profiles.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>URLs dos Posts<textarea style={{width:'100%',minHeight:240}} value={bulkText} onChange={e=>setBulkText(e.target.value)} placeholder="Cole o texto contendo os links aqui..."/></label><em>O sistema extrai os links e preenche automaticamente mÃ©tricas, data e mÃ­dia de cada postagem.</em>{msg&&<p className="bulk-msg">{msg}</p>}<button className="bulk-process" disabled={busy} onClick={process}>{busy?'PROCESSANDO E COLETANDO...':'Links do processador'}</button></div></section>}
function iconFor(x:string){return x==='Painel'?'â—‰':x==='ClassificaÃ§Ã£o'?'â™›':x==='HistÃ³ria'?'â—·':x==='Centro de Controle da MissÃ£o'?'â–¤':x==='Registro de atividades'?'â‰¡':'âš™'}
function DeltaBadge({value}:{value:number}){return value>0?<span className="metric-delta">â†‘ +{Number(value).toLocaleString('pt-BR')}</span>:null}
function ExactStat({label,value,accent=false,delta=0}:{label:string,value:number,accent?:boolean,delta?:number}){return <div className="exact-stat"><small>{label}</small><div className="stat-value-line"><strong className={accent?'accent':''}>{Number(value).toLocaleString('pt-BR')}</strong><DeltaBadge value={delta}/></div></div>}
function FormulaItem({label,value,total=false}:{label:string,value:number,total?:boolean}){return <div className={`formula-item ${total?'total':''}`}><small>{label}</small><strong>+ {Number(value).toLocaleString('pt-BR')} <em>CG</em></strong></div>}

