'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {supabase} from '@/lib/supabase';
import PostLibrary from './post-library';
import AdminPanel from './admin-panel';
import {HistoryPage,ActivityPage,RankingPage} from './tracker-pages-v2';
import MissionControlPage from './mission-control-page';
import {FullSettings,settingsDefaults} from './full-settings';
import {monthlyReward} from '@/lib/reward';
import ReportPage from './report-page';
import ProfileNameGate from './profile-name-gate';
import {refreshStoredPostMetrics} from '@/lib/refresh-post-metrics';
import {postDateKey,postPublishedValue} from '@/lib/post-date';
import './globals.css';import './post-library.css';import './tracker-sections.css';import './video-reference.css';import './screenshot-exact.css';import './interactions.css';import './add-publication.css';

const blank={post_url:'',title:'Publicação do X',views:0,likes:0,reposts:0,comments:0,mission_profile_id:'',image_urls:'',video_url:'',published_date:'',x_published_at:''};
const nav=['Painel','Classificação','História','Centro de Controle da Missão','Registro de atividades','Configurações'];
type Deltas={posts:number;views:number;involvement:number;crystal:number};
let currentMonthlyPostGoal=60;
function rankingCycle(now=new Date()){const cycle=new Date(now.getFullYear(),now.getMonth()+(now.getDate()===1?-1:0),1),next=new Date(cycle.getFullYear(),cycle.getMonth()+1,1),date=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return{month:date(cycle),start:date(new Date(cycle.getFullYear(),cycle.getMonth(),2)),end:date(next),frozen:now.getDate()===1}}

export default function Dashboard({session}:{session:any}){
 const uid=session.user.id;
 const[tab,setTab]=useState(()=>typeof window!=='undefined'?(localStorage.getItem('aoh:last-tab')||'Painel'):'Painel');const[posts,setPosts]=useState<any[]>([]);const[settings,setSettings]=useState<any>(settingsDefaults);const[profiles,setProfiles]=useState<any[]>([]);const[reportOpen,setReportOpen]=useState(false);const[addOpen,setAddOpen]=useState(false);const[bulkOpen,setBulkOpen]=useState(false);const[bulkMission,setBulkMission]=useState('');const[bulkText,setBulkText]=useState('');const[bulkMsg,setBulkMsg]=useState('');const[form,setForm]=useState<any>(blank);const[busy,setBusy]=useState(false);const[autoLoading,setAutoLoading]=useState(false);const[refreshing,setRefreshing]=useState(false);const[refreshStep,setRefreshStep]=useState(1);const[refreshNotice,setRefreshNotice]=useState('');const[deltas,setDeltas]=useState<Deltas>({posts:0,views:0,involvement:0,crystal:0});const[showDeltas,setShowDeltas]=useState(false);const[profileChecked,setProfileChecked]=useState(false);const[isAdmin,setIsAdmin]=useState(false);const[view,setView]=useState<'list'|'cards'>(()=>typeof window!=='undefined'&&localStorage.getItem('aoh:post-view')==='cards'?'cards':'list');const refreshLock=useRef(false);
 const chooseTab=(item:string)=>{setBulkOpen(false);setTab(item);if(typeof window!=='undefined')localStorage.setItem('aoh:last-tab',item)};
 const chooseView=(mode:'list'|'cards')=>{setView(mode);if(typeof window!=='undefined')localStorage.setItem('aoh:post-view',mode)};
 const openAdd=()=>{setForm({...blank,published_date:new Date().toISOString().slice(0,10)});setAddOpen(true)};
 const totalsFor=(rows:any[])=>{const views=rows.reduce((a,p)=>a+Number(p.views||0),0),likes=rows.reduce((a,p)=>a+Number(p.likes||0),0),special=rows.reduce((a,p)=>a+Number(p.special_reward||0),0);return{posts:rows.length,views,involvement:likes,crystal:likes*2+special}};
 const syncRanking=useCallback(async(rows:any[],nextSettings:any)=>{const cycle=rankingCycle();if(!nextSettings.ranking_opt_in){await supabase.from('monthly_rankings').delete().eq('user_id',uid).eq('month',cycle.month);return}if(cycle.frozen)return;const cyclePosts=rows.filter(p=>{const date=postDateKey(postPublishedValue(p));return date>=cycle.start&&date<cycle.end}),cycleReward=monthlyReward(cyclePosts),handle=String(nextSettings.app_name||nextSettings.x_handle||'ANÔNIMO').replace(/^@/,'').trim()||'ANÔNIMO';await supabase.from('monthly_rankings').upsert({user_id:uid,month:cycle.month,x_handle:handle,crystalgin:cycleReward.raw,likes:cycleReward.likes,posts_count:cyclePosts.length,total_views:cycleReward.views,published:true,updated_at:new Date().toISOString()},{onConflict:'user_id,month'})},[uid]);
 const load=useCallback(async(pulse=false)=>{const before=totalsFor(posts);if(pulse){setRefreshing(true);setRefreshStep(1);setShowDeltas(false)}const[{data:p},{data:s},{data:m}]=await Promise.all([supabase.from('posts').select('*').eq('user_id',uid).order('created_at',{ascending:false}),supabase.from('user_settings').select('*').eq('user_id',uid).maybeSingle(),supabase.from('mission_profiles').select('*').eq('user_id',uid).order('name')]);if(pulse)setRefreshStep(2);const next=p||[],nextSettings={...settingsDefaults,...(s||{})};setPosts(next);setSettings(nextSettings);setProfileChecked(true);setProfiles(m||[]);void syncRanking(next,nextSettings);if(!bulkMission&&m?.length)setBulkMission(String(m.find((x:any)=>x.active)?.id||''));if(pulse){const after=totalsFor(next),d={posts:after.posts-before.posts,views:after.views-before.views,involvement:after.involvement-before.involvement,crystal:after.crystal-before.crystal};setDeltas(d);setRefreshing(false);if(Object.values(d).some(v=>v>0)){setShowDeltas(true);setTimeout(()=>setShowDeltas(false),6500)}}},[uid,bulkMission,posts,syncRanking]);
 const refreshMetrics=useCallback(async(source:'manual'|'automatic'='manual')=>{if(refreshLock.current)return false;refreshLock.current=true;setRefreshing(true);setRefreshStep(1);setRefreshNotice('');setShowDeltas(false);const before=totalsFor(posts);try{const result=await refreshStoredPostMetrics(posts,uid);setRefreshStep(2);const{data:freshPosts,error:freshError}=await supabase.from('posts').select('*').eq('user_id',uid).order('created_at',{ascending:false});if(freshError)throw freshError;const next=freshPosts||[];setPosts(next);void syncRanking(next,settings);const after=totalsFor(next),d={posts:after.posts-before.posts,views:after.views-before.views,involvement:after.involvement-before.involvement,crystal:after.crystal-before.crystal};setDeltas(d);if(Object.values(d).some(v=>v>0)){setShowDeltas(true);setTimeout(()=>setShowDeltas(false),6500)}const success=result.attempted===0||result.succeeded>0;if(source==='manual'&&success&&settings.show_refresh_timer){const now=new Date(),hours=Math.max(.5,Number(settings.refresh_interval)||.5),nextRefresh=new Date(now.getTime()+hours*3600000);const{error}=await supabase.from('user_settings').update({last_refresh_at:now.toISOString(),next_refresh_at:nextRefresh.toISOString()}).eq('user_id',uid);if(!error)window.dispatchEvent(new CustomEvent('aoh:auto-refresh-changed',{detail:{active:true,hours}}))}setRefreshNotice(result.failed?`${result.succeeded} de ${result.attempted} publicações atualizadas.`:`${result.succeeded} publicação(ões) atualizada(s) com sucesso.`);return success}catch{setRefreshNotice('Não foi possível atualizar as métricas agora.');return false}finally{refreshLock.current=false;setRefreshing(false)}},[posts,uid,settings,syncRanking]);
 useEffect(()=>{load()},[]);
 useEffect(()=>{let active=true;supabase.from('admin_users').select('user_id').eq('user_id',uid).maybeSingle().then(({data})=>{if(active)setIsAdmin(Boolean(data))});return()=>{active=false}},[uid]);
 useEffect(()=>{const open=()=>setReportOpen(true);window.addEventListener('aoh:open-report',open);return()=>window.removeEventListener('aoh:open-report',open)},[]);
 useEffect(()=>{const automatic=(event:Event)=>{const detail=(event as CustomEvent<{handled?:boolean;complete?:(success:boolean)=>void}>).detail||{};detail.handled=true;refreshMetrics('automatic').then(success=>detail.complete?.(success))};window.addEventListener('aoh:refresh-metrics',automatic);return()=>window.removeEventListener('aoh:refresh-metrics',automatic)},[refreshMetrics]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'&&addOpen)setAddOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[addOpen]);
 useEffect(()=>{if(!refreshNotice)return;const timer=window.setTimeout(()=>setRefreshNotice(''),6000);return()=>window.clearTimeout(timer)},[refreshNotice]);
 async function fetchPostData(url:string){const r=await fetch('/api/x-metrics',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});const data=await r.json();if(!r.ok||data.error)throw new Error(data.error||'Falha na coleta');return data}
 useEffect(()=>{if(!addOpen||!/https?:\/\/(?:www\.)?(?:x\.com|twitter\.com)\/[^/]+\/status\/\d+/i.test(form.post_url||''))return;let alive=true;const timer=setTimeout(async()=>{setAutoLoading(true);try{const d=await fetchPostData(form.post_url);if(alive)setForm((f:any)=>({...f,title:d.title||f.title,views:Number(d.views||0),likes:Number(d.likes||0),reposts:Number(d.reposts||0),comments:Number(d.comments||0),published_date:d.published_date||f.published_date,x_published_at:d.published_at||f.x_published_at,image_urls:Array.isArray(d.image_urls)?d.image_urls.join('\n'):f.image_urls,video_url:d.video_url||f.video_url}))}catch{}finally{if(alive)setAutoLoading(false)}},450);return()=>{alive=false;clearTimeout(timer)}},[addOpen,form.post_url]);
 const reward=useMemo(()=>monthlyReward(posts),[posts]);
 const crystalginLimit=Math.max(1,Number(settings.cap_unlocked?settings.crystalgin_limit:30000)||30000);
 const crystalginProgress=Math.min(reward.raw,crystalginLimit);
 currentMonthlyPostGoal=Math.max(1,Number((typeof window!=='undefined'&&localStorage.getItem(`aoh:monthly-goal:${uid}`))||settings.monthly_post_goal||60));
 const reposts=posts.reduce((a,p)=>a+Number(p.reposts||0),0),comments=posts.reduce((a,p)=>a+Number(p.comments||0),0),involvement=reward.likes;
 const missionRows=useMemo(()=>{const map=new Map<string,{name:string,color:string,posts:number,views:number,likes:number,crystalgin:number}>();for(const p of posts){const name=p.mission_name||'SEM MISSÃO';const profile=profiles.find(x=>x.name===name);const r=map.get(name)||{name,color:profile?.color||'#f6ad55',posts:0,views:0,likes:0,crystalgin:0};r.posts++;r.views+=Number(p.views||0);r.likes+=Number(p.likes||0);r.crystalgin+=Number(p.special_reward||0)+Number(p.likes||0)*2;map.set(name,r)}return [...map.values()]},[posts,profiles]);
 const missionTotals=useMemo(()=>missionRows.reduce((a,r)=>({posts:a.posts+r.posts,views:a.views+r.views,likes:a.likes+r.likes,crystalgin:a.crystalgin+r.crystalgin}),{posts:0,views:0,likes:0,crystalgin:0}),[missionRows]);
 for(const row of missionRows){if(row.name.trim().toLowerCase()==='hight quality')row.name='High Quality'}
 const selectedMission=profiles.find(x=>String(x.id)===String(form.mission_profile_id));
 async function addPost(){if(!form.post_url.trim())return;setBusy(true);const mp=profiles.find(x=>String(x.id)===String(form.mission_profile_id));const imgs=String(form.image_urls||'').split(/[\n,]/).map((x:string)=>x.trim()).filter(Boolean);await supabase.from('posts').insert({user_id:uid,title:form.title.trim()||'Publicação do X',post_url:form.post_url.trim(),published_at:form.published_date||new Date().toISOString().slice(0,10),x_published_at:form.x_published_at||null,views:Number(form.views),likes:Number(form.likes),reposts:Number(form.reposts),comments:Number(form.comments),mission_profile_id:mp?.id||null,mission_name:mp?.name||null,special_reward:Number(mp?.reward||0),network:'X',image_urls:imgs,video_url:form.video_url||null,author_handle:settings.x_handle||null,metrics_source:'auto',metrics_updated_at:new Date().toISOString()});setBusy(false);setAddOpen(false);setForm(blank);await load(true)}
 async function processBulk(){const urls=[...new Set((bulkText.match(/https?:\/\/[^\s]+/g)||[]).map(x=>x.replace(/[),.;]+$/,'')))].filter(x=>/https?:\/\/(www\.)?(x\.com|twitter\.com)\//i.test(x));if(!urls.length){setBulkMsg('Nenhum link válido do X foi encontrado.');return}setBusy(true);setBulkMsg(`Coletando dados de ${urls.length} publicação(ões)...`);const mp=profiles.find(x=>String(x.id)===String(bulkMission));const rows=await Promise.all(urls.map(async url=>{let d:any={};try{d=await fetchPostData(url)}catch{}return{user_id:uid,title:d.title||'Publicação do X',post_url:url,published_at:String(d.published_date||d.published_at||'').slice(0,10)||new Date().toISOString().slice(0,10),x_published_at:d.published_at||null,views:Number(d.views||0),likes:Number(d.likes||0),reposts:Number(d.reposts||0),comments:Number(d.comments||0),mission_profile_id:mp?.id||null,mission_name:mp?.name||null,special_reward:Number(mp?.reward||0),network:'X',author_handle:d.author_handle||settings.x_handle||null,image_urls:Array.isArray(d.image_urls)?d.image_urls:[],video_url:d.video_url||null,metrics_source:d.source||'auto',metrics_updated_at:new Date().toISOString()}}));const{error}=await supabase.from('posts').insert(rows);setBusy(false);if(error){setBulkMsg('Não foi possível adicionar os links.');return}setBulkMsg(`${urls.length} publicação(ões) adicionada(s) com preenchimento automático.`);setBulkText('');await load(true)}
 async function closeMonth(){if(!confirm('Fechar o período atual?'))return;const d=new Date(),month=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`;await supabase.from('archived_periods').insert({user_id:uid,month,summary:{total:crystalginProgress,total_raw:reward.raw,crystalgin_limit:crystalginLimit,posts:posts.length,views:reward.views,likes:reward.likes,reposts,comments,base:reward.base,viewsReward:reward.viewsReward,engagementReward:reward.engagementReward,special:reward.special},posts_snapshot:posts});chooseTab('História')}
 async function signOut(){await supabase.auth.signOut()}
 const username=String(settings.app_name||'').trim().toUpperCase();
 if(reportOpen)return <ReportPage posts={posts} profiles={profiles} settings={settings} onCancel={()=>setReportOpen(false)}/>;
 return <div className="exact-app">
  <header className="exact-topbar"><div className="exact-brand">AVALIAÇÃO&nbsp;DE&nbsp;MÉTRICAS</div>{refreshing?<div className="refresh-pill"><span className="refresh-spin">↻</span><span>ATUALIZANDO MÉTRICAS<br/><b>({refreshStep}/2)</b></span></div>:<div className="wait-pill">●&nbsp; ESPERA</div>}<nav className="exact-nav">{[...nav,...(isAdmin?['Admin']:[])].map(item=><button key={item} className={tab===item?'active':''} onClick={()=>chooseTab(item)}><span className="nav-icon">{iconFor(item)}</span><span>{item==='História'?'Histórico':item}</span></button>)}</nav><button className="user-pill" onClick={signOut}><span>◉</span>{username}</button></header>
  <main className="exact-main">
   {bulkOpen?<BulkPosts profiles={profiles} bulkMission={bulkMission} setBulkMission={setBulkMission} bulkText={bulkText} setBulkText={setBulkText} busy={busy} msg={bulkMsg} process={processBulk} back={()=>setBulkOpen(false)}/>:<>
   {tab==='Painel'&&<>
    <section className="exact-hero"><div className="hero-title"><h1>PAINEL</h1><span>{posts.length}</span></div><div className="hero-actions"><button>⇩ <b>IMPORTAR</b></button><div className="split-btn"><button>JSON</button><button>CSV</button></div><button className="report-btn">▤ <b>RELATÓRIO</b></button><button onClick={()=>setBulkOpen(true)}>▤ <b>ADIÇÃO EM MASSA</b></button><button className="blue-btn" onClick={closeMonth}>◴ <b>FECHAR MÊS</b></button><button className={`green-btn ${refreshing?'is-refreshing':''}`} disabled={refreshing} onClick={()=>refreshMetrics('manual')}>↻ <b>{refreshing?'ATUALIZANDO MÉTRICAS...':'ATUALIZAR AGORA (MANUAL)'}</b></button><button className="orange-add" onClick={openAdd}>＋ <b>ADICIONAR PUBLICAÇÃO</b></button></div>{refreshNotice&&<p style={{margin:'10px 0 0',textAlign:'right',color:'#8fa99e',fontSize:10,fontWeight:800}}>{refreshNotice}</p>}</section>
    <section className="exact-stats"><ExactStat label="TOTAL DE PUBLICAÇÕES" value={posts.length} delta={showDeltas?deltas.posts:0}/><ExactStat label="VISUALIZAÇÕES TOTAIS" value={reward.views} delta={showDeltas?deltas.views:0}/><div className="exact-stat progress-stat"><div className="stat-label-row"><small>PROGRESSO DE<br/>CRYSTGIN</small><span>FÓRMULA<br/>OFICIAL</span></div><div className="stat-value-line"><AnimatedNumber value={crystalginProgress} suffix={` / ${crystalginLimit.toLocaleString('pt-BR')}`}/>{showDeltas&&deltas.crystal>0&&<DeltaBadge value={deltas.crystal}/>}</div><div className="progress-line"><i style={{width:`${Math.min(100,crystalginProgress/crystalginLimit*100)}%`}}/></div></div><ExactStat label="CURTIDAS TOTAIS" hint="Soma de todas as curtidas" value={involvement} delta={showDeltas?deltas.involvement:0}/><ExactStat label="CRYSTGIN TOTAL" value={reward.raw} accent delta={showDeltas?deltas.crystal:0}/></section>
    <section className="formula-strip"><div className="formula-label">FÓRMULA V2</div><div className="formula-caption">DETALHAMENTO DA RECOMPENSA OFICIAL</div><FormulaItem label="BÁSICO (MAIS DE 10 POSTS)" value={reward.base}/><FormulaItem label="VISUALIZAR (COLHEITA)" value={reward.viewsReward}/><FormulaItem label="ENGAJAMENTO (CURTIDAS X2)" value={reward.engagementReward}/><FormulaItem label="MISSÕES ESPECIAIS" value={reward.special}/><FormulaItem label="TOTAL SEM CAP" value={reward.raw} total/></section>
    <section className="mission-table mission-summary-card"><div className="mission-head"><h2>DESEMPENHO POR MISSÃO</h2><span>RESUMO POR CATEGORIA</span></div><div className="mission-row mission-columns"><b>MISSÃO</b><b>POSTAGENS</b><b>IMPRESSÕES/VISUALIZAÇÕES TOTAIS</b><b>CURTIDAS</b><b>CRYSTGIN</b></div>{missionRows.map(r=><div className="mission-row" key={r.name}><div className="mission-name"><i style={{background:r.color,boxShadow:`0 0 10px ${r.color}`}}/><strong>{r.name}</strong></div><span>{r.posts}</span><span>{r.views.toLocaleString('pt-BR')}</span><span>{r.likes.toLocaleString('pt-BR')}</span><strong className="orange-text">{r.crystalgin.toLocaleString('pt-BR')}</strong></div>)}{!missionRows.length&&<div className="mission-empty">Nenhuma missão com publicações.</div>}<div className="mission-row mission-total-row"><strong>TOTAL</strong><strong>{missionTotals.posts.toLocaleString('pt-BR')}</strong><strong>{missionTotals.views.toLocaleString('pt-BR')}</strong><strong>{missionTotals.likes.toLocaleString('pt-BR')}</strong><strong>{missionTotals.crystalgin.toLocaleString('pt-BR')}</strong></div><div className="mission-reward-summary"><div className="mission-reward-line"><span>RECOMPENSA BÁSICA <small>(MÍN. 10 POSTAGENS)</small></span><strong>+ {reward.base.toLocaleString('pt-BR')} <em>CG</em></strong></div><div className="mission-reward-line"><span>BÔNUS DE VISUALIZAÇÕES <small>(COLHETES)</small></span><strong>+ {reward.viewsReward.toLocaleString('pt-BR')} <em>CG</em></strong></div><div className="mission-official-divider"/><div className="mission-official-total"><span>PROGRESSO OFICIAL <small>(COM LIMITE)</small></span><strong>{crystalginProgress.toLocaleString('pt-BR')} <em>CG</em></strong></div></div></section>
    {posts.length>0&&<section className="exact-posts"><div className="posts-head"><h2>PUBLICAÇÕES</h2><div><button className={view==='list'?'active':''} onClick={()=>chooseView('list')}>LISTA</button><button className={view==='cards'?'active':''} onClick={()=>chooseView('cards')}>CARTÕES</button></div></div><div className={`post-view ${view}`}><PostLibrary userId={uid} posts={posts} reload={load} view={view} profiles={profiles} crystalginLimit={crystalginLimit}/></div></section>}
   </>}
   {tab==='Classificação'&&<RankingPage/>}{tab==='História'&&<HistoryPage uid={uid}/>} {tab==='Centro de Controle da Missão'&&<MissionControlPage uid={uid} reloadProfiles={load}/>} {tab==='Registro de atividades'&&<ActivityPage uid={uid}/>} {tab==='Configurações'&&<FullSettings uid={uid} settings={settings} setSettings={setSettings}/>} {isAdmin&&tab==='Admin'&&<AdminPanel/>}</>}
  </main>
  <ProfileNameGate userId={uid} open={profileChecked&&!settings.profile_name_confirmed} initialName={settings.app_name||''} onSaved={name=>setSettings((current:any)=>({...current,app_name:name,profile_name_confirmed:true}))}/>
  {addOpen&&<div className="add-publication-screen" onMouseDown={e=>{if(e.target===e.currentTarget)setAddOpen(false)}}><div className="add-publication-shell" onMouseDown={e=>e.stopPropagation()}><div className="add-publication-heading"><div className="add-publication-plus">＋</div><div><h2>Enviar nova publicação</h2><p>{autoLoading?'Coletando automaticamente os dados da postagem...':'Cole o link do X e os dados serão preenchidos automaticamente.'}</p></div></div><section className="add-publication-card"><label className="add-field">URL da postagem<input autoFocus value={form.post_url} onChange={e=>setForm({...form,post_url:e.target.value})} placeholder="https://x.com/your-post"/></label><div className="add-group-label">Métricas de engajamento</div><div className="add-metrics-grid"><MetricInput icon="◉" value={form.views} onChange={v=>setForm({...form,views:v})}/><MetricInput icon="◯" value={form.comments} onChange={v=>setForm({...form,comments:v})}/><MetricInput icon="↔" value={form.reposts} onChange={v=>setForm({...form,reposts:v})}/><MetricInput icon="♥" heart value={form.likes} onChange={v=>setForm({...form,likes:v})}/></div><div className="add-two-column"><label className="add-field">Data da publicação no X<div className="add-input-icon"><span>▣</span><input type="date" value={form.published_date||''} disabled title="Data obtida automaticamente pelo link da publicação no X"/></div></label><label className="add-field">Missão<div className="add-mission-select"><i style={{background:selectedMission?.color||'#38d27f'}}/><select value={form.mission_profile_id} onChange={e=>setForm({...form,mission_profile_id:e.target.value})}><option value="">Sem missão especial</option>{profiles.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div></label></div><div className="add-group-label add-bonus-title">Bônus</div><div className="add-bonus-row"><label className="locked-bonus"><input type="checkbox" disabled/><span/>Imagem em destaque</label><label className="locked-bonus"><input type="checkbox" disabled/><span/>Bônus de Reprodução</label></div><button className="add-submit" disabled={busy||autoLoading||!form.post_url.trim()} onClick={addPost}>＋ <b>{autoLoading?'COLETANDO...':busy?'ADICIONANDO...':'Adicionar publicação'}</b></button></section></div></div>}
 </div>
}
function MetricInput({icon,value,onChange,heart=false}:{icon:string;value:number;onChange:(v:number)=>void;heart?:boolean}){return <div className="add-metric-input"><span className={heart?'heart':''}>{icon}</span><input type="number" min="0" value={value} onChange={e=>onChange(Number(e.target.value))}/></div>}
function BulkPosts({profiles,bulkMission,setBulkMission,bulkText,setBulkText,busy,msg,process,back}:{profiles:any[];bulkMission:string;setBulkMission:(v:string)=>void;bulkText:string;setBulkText:(v:string)=>void;busy:boolean;msg:string;process:()=>void;back:()=>void}){return <section className="bulk-page" style={{maxWidth:760,margin:'16px auto'}}><div className="bulk-title"><button onClick={back}>▤</button><div><h1>Postagens em Massa</h1><p>Cole uma lista de URLs de postagens abaixo, uma por linha. As métricas e mídias serão coletadas automaticamente.</p></div></div><div className="bulk-card" style={{background:'#1c1c1c',border:'1px solid #2b2b2b',borderRadius:8,padding:30}}><label>Missão Padrão para Novos Posts<select value={bulkMission} onChange={e=>setBulkMission(e.target.value)}><option value="">Sem missão especial</option>{profiles.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>URLs dos Posts<textarea style={{width:'100%',minHeight:240}} value={bulkText} onChange={e=>setBulkText(e.target.value)} placeholder="Cole o texto contendo os links aqui..."/></label><em>O sistema extrai os links e preenche automaticamente métricas, data e mídia de cada postagem.</em>{msg&&<p className="bulk-msg">{msg}</p>}<button className="bulk-process" disabled={busy} onClick={process}>{busy?'PROCESSANDO E COLETANDO...':'Links do processador'}</button></div></section>}
function iconFor(x:string){return x==='Painel'?'◉':x==='Classificação'?'♛':x==='História'?'◷':x==='Centro de Controle da Missão'?'▤':x==='Registro de atividades'?'≡':x==='Admin'?'◆':'⚙'}
function DeltaBadge({value}:{value:number}){return value>0?<span className="metric-delta">↑ +{Number(value).toLocaleString('pt-BR')}</span>:null}
function AnimatedNumber({value,suffix='',accent=false}:{value:number;suffix?:string;accent?:boolean}){const[display,setDisplay]=useState(Number(value)||0),[counting,setCounting]=useState(false),previous=useRef(Number(value)||0),first=useRef(true);useEffect(()=>{const target=Number(value)||0,start=previous.current;previous.current=target;if(first.current){first.current=false;setDisplay(target);return}if(start===target||window.matchMedia('(prefers-reduced-motion: reduce)').matches){setDisplay(target);return}let frame=0,began=0;setCounting(true);const tick=(time:number)=>{if(!began)began=time;const progress=Math.min(1,(time-began)/1350),eased=1-Math.pow(1-progress,3);setDisplay(Math.round(start+(target-start)*eased));if(progress<1)frame=requestAnimationFrame(tick);else setCounting(false)};frame=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(frame);setCounting(false)}},[value]);return <strong className={accent?'accent':''}><span className={`metric-number-digits ${counting?'is-counting':''}`}>{display.toLocaleString('pt-BR')}</span>{suffix&&<em>{suffix}</em>}</strong>}
function ExactStat({label,value,accent=false,delta=0,hint}:{label:string,value:number,accent?:boolean,delta?:number,hint?:string}){const isPostTotal=label==='TOTAL DE PUBLICAÇÕES';return <div className="exact-stat" title={hint}><small>{label}</small>{hint&&<span className="stat-hint">{hint}</span>}<div className="stat-value-line"><AnimatedNumber value={value} accent={accent} suffix={isPostTotal?` / ${currentMonthlyPostGoal.toLocaleString('pt-BR')}`:''}/><DeltaBadge value={delta}/></div></div>}
function FormulaItem({label,value,total=false}:{label:string,value:number,total?:boolean}){return <div className={`formula-item ${total?'total':''}`}><small>{label}</small><strong>+ {Number(value).toLocaleString('pt-BR')} <em>CG</em></strong></div>}

