'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {useEscapeClose} from '@/lib/use-escape-close';
import {postContribution,monthlyReward} from '@/lib/reward';
import XPostPreview,{VideoPreview} from './x-post-preview';
import './x-post-preview.css';
import './post-experience.css';

type MissionProfile={id?:string|number;name?:string;reward?:number;active?:boolean;description?:string;multiplier?:number;limit?:string|number|null};

export default function PostLibrary({userId,posts,reload,view,profiles=[],capUnlocked=false}:{userId:string;posts:any[];reload:()=>Promise<void>;view?:'list'|'cards';profiles?:MissionProfile[];capUnlocked?:boolean}){
 const[expanded,setExpanded]=useState<any>(null);const[edit,setEdit]=useState<any>(null);const[menuId,setMenuId]=useState<any>(null);const[selectedIds,setSelectedIds]=useState<Set<string>>(new Set());const[deletingSelected,setDeletingSelected]=useState(false);const selectAllRef=useRef<HTMLInputElement>(null);useEscapeClose(!!edit,()=>setEdit(null));
 const effectiveView=view||(typeof window!=='undefined'&&localStorage.getItem('aoh:post-view')==='cards'?'cards':'list');const reward=monthlyReward(posts,capUnlocked);const missionCrystal=posts.reduce((a,p)=>a+postContribution(p),0);
 const selectableIds=useMemo(()=>posts.map(p=>String(p.id)),[posts]);const selectedCount=selectedIds.size;const allSelected=selectableIds.length>0&&selectableIds.every(id=>selectedIds.has(id));const someSelected=selectedCount>0&&!allSelected;
 useEffect(()=>{setSelectedIds(prev=>{const allowed=new Set(selectableIds);const next=new Set([...prev].filter(id=>allowed.has(id)));return next.size===prev.size?[...next].every(id=>prev.has(id))?prev:next:next})},[selectableIds]);
 useEffect(()=>{if(selectAllRef.current)selectAllRef.current.indeterminate=someSelected},[someSelected]);
 useEffect(()=>{const close=()=>setMenuId(null);window.addEventListener('click',close);return()=>window.removeEventListener('click',close)},[]);
 async function save(){if(!edit)return;await supabase.from('posts').update({title:edit.title,post_url:edit.post_url,views:Number(edit.views),likes:Number(edit.likes),reposts:Number(edit.reposts),comments:Number(edit.comments),video_url:edit.video_url||null}).eq('id',edit.id).eq('user_id',userId);setEdit(null);await reload()}
 async function removePost(p:any){if(!p?.id)return;if(!confirm('Excluir esta publicação? Esta ação não pode ser desfeita.'))return;const{error}=await supabase.from('posts').delete().eq('id',p.id).eq('user_id',userId);if(error){alert('Não foi possível excluir a publicação.');return}setSelectedIds(prev=>{const next=new Set(prev);next.delete(String(p.id));return next});setExpanded(null);setMenuId(null);if(edit?.id===p.id)setEdit(null);await reload()}
 function toggleOne(id:any){const key=String(id);setSelectedIds(prev=>{const next=new Set(prev);if(next.has(key))next.delete(key);else next.add(key);return next})}
 function toggleAll(){setSelectedIds(allSelected?new Set():new Set(selectableIds))}
 async function removeSelected(){if(!selectedCount||deletingSelected)return;const ids=[...selectedIds];if(!confirm(`Excluir ${selectedCount} publicação(ões) selecionada(s)? Esta ação não pode ser desfeita.`))return;setDeletingSelected(true);const{error}=await supabase.from('posts').delete().in('id',ids).eq('user_id',userId);setDeletingSelected(false);if(error){alert('Não foi possível excluir as publicações selecionadas.');return}if(expanded&&selectedIds.has(String(expanded)))setExpanded(null);if(edit?.id&&selectedIds.has(String(edit.id)))setEdit(null);setSelectedIds(new Set());await reload()}
 if(effectiveView==='list')return <><SummaryTail posts={posts} reward={reward} missionCrystal={missionCrystal}/><div className="ref-list">{selectedCount>0&&<div className="ref-selection-bar"><strong>{selectedCount} selecionado{selectedCount===1?'':'s'}</strong><button type="button" disabled={deletingSelected} onClick={removeSelected}>🗑 {deletingSelected?'EXCLUINDO...':'EXCLUIR SELECIONADOS'}</button></div>}<div className="ref-list-head"><input ref={selectAllRef} className="ref-select-check" type="checkbox" checked={allSelected} onChange={toggleAll} aria-label="Selecionar todas as publicações"/><b>POST⌄</b><b>ENGAJAMENTO</b><b>CURTIDAS</b><b>COMENTÁRIOS</b><b>REPOSTS</b><b>VIEWS</b><b>CRYSTGIN</b><b>AÇÕES</b></div>{posts.map(p=>{const engagement=Number(p.likes||0)+Number(p.comments||0)+Number(p.reposts||0);const selected=selectedIds.has(String(p.id));const missionProfile=findMissionProfile(p,profiles);return <div className={`ref-list-row${selected?' selected':''}`} key={p.id}><input className="ref-select-check" type="checkbox" checked={selected} onChange={()=>toggleOne(p.id)} aria-label={`Selecionar ${p.title||'publicação'}`}/><div className="ref-post-cell"><button type="button" className="ref-edit-square" onClick={()=>setEdit({...p})} aria-label="Editar publicação">✎</button><div><strong>𝕏 <span>{p.mission_name||p.title||'Publicação'}</span> ↗</strong><small>{formatDate(p.created_at)}</small></div></div><b>{engagement.toLocaleString('pt-BR')}</b><span>{Number(p.likes||0).toLocaleString('pt-BR')}</span><span>{Number(p.comments||0).toLocaleString('pt-BR')}</span><span>{Number(p.reposts||0).toLocaleString('pt-BR')}</span><span>{Number(p.views||0).toLocaleString('pt-BR')}</span><strong className="ref-orange">{postContribution(p).toLocaleString('pt-BR')}</strong><div className="post-actions-menu-wrap" onClick={e=>e.stopPropagation()}><button type="button" className="ref-more" onClick={()=>setMenuId(menuId===p.id?null:p.id)} aria-label="Abrir ações da publicação">•••</button>{menuId===p.id&&<div className="post-actions-menu"><button type="button" onClick={()=>{setEdit({...p});setMenuId(null)}}>✎ Editar publicação</button><button type="button" onClick={()=>{setExpanded(expanded===p.id?null:p.id);setMenuId(null)}}>{expanded===p.id?'− Recolher detalhes':'＋ Expandir detalhes'}</button><button type="button" className="danger" onClick={()=>removePost(p)}>🗑 Excluir publicação</button></div>}</div>{expanded===p.id&&<div className="ref-expanded"><ExpandedPost p={p} reward={reward} missionProfile={missionProfile} capUnlocked={capUnlocked} onDelete={()=>removePost(p)}/></div>}</div>})}</div>{edit&&<EditPostModal edit={edit} setEdit={setEdit} save={save}/>}</>;
 return <><SummaryTail posts={posts} reward={reward} missionCrystal={missionCrystal}/><div className="ref-card-grid">{posts.map(p=><article className="ref-card" key={p.id}><div className="ref-media"><span className="x-badge">𝕏</span><Media p={p}/><button className="ref-open" onClick={()=>window.open(p.post_url,'_blank','noopener,noreferrer')}>↗</button></div><div className="ref-card-info"><strong className="ref-mission">{p.mission_name||p.title||'PUBLICAÇÃO'}</strong><small>{formatDate(p.created_at)}</small><div className="ref-inline-metrics"><span>◉ {Number(p.views||0).toLocaleString('pt-BR')}</span><span>◯ {Number(p.comments||0).toLocaleString('pt-BR')}</span><span>↻ {Number(p.reposts||0).toLocaleString('pt-BR')}</span><span className="heart">♥ {Number(p.likes||0).toLocaleString('pt-BR')}</span></div></div><div className="ref-card-foot"><span>⌁ <b>{Number(p.likes||0).toLocaleString('pt-BR')}</b></span><strong>{postContribution(p).toLocaleString('pt-BR')}</strong><small>Crystgin</small><button className="ref-pencil" onClick={()=>setEdit({...p})}>✎</button></div></article>)}</div>{edit&&<EditPostModal edit={edit} setEdit={setEdit} save={save}/>}</>;
}
function SummaryTail({posts,reward,missionCrystal}:{posts:any[];reward:any;missionCrystal:number}){return <div className="ref-summary-tail"><div className="ref-summary-total"><b>TOTAL</b><strong>{posts.length}</strong><strong>{reward.views.toLocaleString('pt-BR')}</strong><strong>{reward.likes.toLocaleString('pt-BR')}</strong><strong>{missionCrystal.toLocaleString('pt-BR')}</strong></div><div className="ref-reward-line"><span>RECOMPENSA BÁSICA (MÍN. 10 POSTAGENS)</span><b>+ {reward.base.toLocaleString('pt-BR')} CG</b></div><div className="ref-reward-line"><span>BÔNUS DE VISUALIZAÇÕES (COLCHETES)</span><b>+ {reward.viewsReward.toLocaleString('pt-BR')} CG</b></div><div className="ref-official"><strong>TOTAL OFICIAL (COM CAP)</strong><b>{reward.total.toLocaleString('pt-BR')}</b></div></div>}
export function EditPostModal({edit,setEdit,save}:{edit:any;setEdit:(v:any)=>void;save:()=>void}){return <div className="edit-post-overlay" role="presentation" onMouseDown={e=>{if(e.currentTarget===e.target)setEdit(null)}}><section className="edit-post-modal" role="dialog" aria-modal="true" aria-labelledby="edit-post-title"><div className="edit-post-head"><div><h2 id="edit-post-title">EDITAR POST</h2><p>Atualize as métricas de engajamento e outros detalhes do post.</p></div><button type="button" className="edit-post-close" onClick={()=>setEdit(null)} aria-label="Fechar">×</button></div><div className="edit-post-scroll"><XPostPreview post={edit}/><div className="edit-post-fields"><label>Título / texto<input value={edit.title||''} onChange={e=>setEdit({...edit,title:e.target.value})}/></label><label>Link<input value={edit.post_url||''} onChange={e=>setEdit({...edit,post_url:e.target.value})}/></label><div className="metric-input-grid">{[['Visualizações','views'],['Curtidas','likes'],['Reposts','reposts'],['Comentários','comments']].map(([label,k])=><label key={k}>{label}<input type="number" min="0" value={edit[k]||0} onChange={e=>setEdit({...edit,[k]:Number(e.target.value)})}/></label>)}</div><label>URL do vídeo<input value={edit.video_url||''} onChange={e=>setEdit({...edit,video_url:e.target.value})}/></label><div className="edit-post-actions"><button type="button" className="cancel" onClick={()=>setEdit(null)}>CANCELAR</button><button type="button" className="save" onClick={save}>SALVAR ALTERAÇÕES</button></div></div></div></section></div>}
function formatDate(v:any){if(!v)return'';try{return new Date(v).toLocaleDateString('pt-BR')}catch{return''}}
function Media({p}:{p:any}){const imgs=Array.isArray(p.image_urls)?p.image_urls.filter(Boolean):[];if(p.video_url)return <VideoPreview url={p.video_url} poster={p.thumbnail_url} postUrl={p.post_url}/>;if(imgs.length)return <img src={imgs[0]} alt="Mídia da publicação"/>;return <div className="ref-media-empty">𝕏</div>}
function findMissionProfile(post:any,profiles:MissionProfile[]){return profiles.find(profile=>String(profile.id)===String(post.mission_profile_id))||profiles.find(profile=>profile.name===post.mission_name)}
function ExpandedPost({p,reward,missionProfile,capUnlocked,onDelete}:{p:any;reward:any;missionProfile?:MissionProfile;capUnlocked:boolean;onDelete:()=>void}){return <div className="post-expanded-shell"><PostExpandedDetails p={p} reward={reward} missionProfile={missionProfile} capUnlocked={capUnlocked} onDelete={onDelete}/><XPostPreview post={p}/></div>}
export function PostExpandedDetails({p,reward,missionProfile,capUnlocked,onDelete}:{p:any;reward:any;missionProfile?:MissionProfile;capUnlocked:boolean;onDelete:()=>void}){const likes=Number(p.likes||0),special=Number(p.special_reward||0),contrib=postContribution(p),mission=missionProfile?.name||p.mission_name||'SEM MISSÃO',limit=missionProfile?.limit??p.mission_limit??'Ilimitado',description=missionProfile?.description||p.mission_description||'Engajamento calculado pela Fórmula Oficial V2: Curtidas × 2, somado ao bônus especial quando aplicável.';return <section className="post-expanded-info"><div className="mission-overview"><small>PERFIL / MISSÃO</small><h3>{mission}</h3><p>{description}</p></div><div className="mission-rule-grid"><div><small>MULTIPLICADOR</small><b>× 2</b></div><div><small>BÔNUS</small><b>{special.toLocaleString('pt-BR')} CG</b></div><div><small>LIMITE</small><b>{String(limit)}</b></div></div><div className="calc-detail-head"><div><span className="formula-badge">FÓRMULA OFICIAL V2</span><h4>Detalhamento do Cálculo de Crystgin</h4></div><strong>◆ {contrib.toLocaleString('pt-BR')} CG</strong></div><div className="calc-detail-grid"><div><small>CONTRIBUIÇÃO INDIVIDUAL</small><b>{contrib.toLocaleString('pt-BR')} CG</b></div><div><small>VIEWS</small><b>{Number(p.views||0).toLocaleString('pt-BR')}</b></div><div><small>CURTIDAS × 2</small><b>{(likes*2).toLocaleString('pt-BR')} CG</b></div><div><small>RECOMPENSA BÁSICA</small><b>{reward.base.toLocaleString('pt-BR')} CG mensal</b></div><div><small>RECOMPENSA DE VIEWS</small><b>{reward.viewsReward.toLocaleString('pt-BR')} CG mensal</b></div><div><small>RECOMPENSA DE ENGAJAMENTO</small><b>{(likes*2).toLocaleString('pt-BR')} CG desta publicação</b></div><div><small>MISSÕES ESPECIAIS</small><b>{special.toLocaleString('pt-BR')} CG</b></div><div className="calc-total"><small>CRYSTGIN TOTAL</small><b>{contrib.toLocaleString('pt-BR')} CG</b></div><div><small>CAP MENSAL</small><b>{capUnlocked?'Desbloqueado':'30.000 CG'}</b></div><div className="calc-month-total"><small>TOTAL MENSAL OFICIAL</small><b>{reward.total.toLocaleString('pt-BR')} CG</b></div></div><div className="post-expanded-actions"><button type="button" className="post-delete-button" onClick={onDelete}>🗑 EXCLUIR PUBLICAÇÃO</button></div></section>}

