'use client';
import {useRef,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {useEscapeClose} from '@/lib/use-escape-close';
import {postContribution} from '@/lib/reward';
export default function PostLibrary({userId,posts,reload}:{userId:string,posts:any[],reload:()=>Promise<void>}){const[expanded,setExpanded]=useState<any>(null);const[edit,setEdit]=useState<any>(null);useEscapeClose(!!edit,()=>setEdit(null));
async function save(){if(!edit)return;await supabase.from('posts').update({title:edit.title,post_url:edit.post_url,views:Number(edit.views),likes:Number(edit.likes),reposts:Number(edit.reposts),comments:Number(edit.comments),video_url:edit.video_url||null}).eq('id',edit.id).eq('user_id',userId);setEdit(null);await reload()}
async function remove(id:number){if(!confirm('Excluir esta publicação?'))return;await supabase.from('posts').delete().eq('id',id).eq('user_id',userId);await reload()}
return <div className="post-library">{posts.map(p=><article className="post-card video-card" key={p.id}><div className="post-card-head" onClick={()=>setExpanded(expanded===p.id?null:p.id)}><div className="post-card-title"><div className="post-author"><span className="avatar">{String(p.author_handle||'X').slice(0,1).toUpperCase()}</span><div><strong>{p.title||'Publicação do X'}</strong><a href={p.post_url} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>{p.author_handle?'@'+p.author_handle:p.post_url}</a></div></div><div className="post-card-meta"><span>◉ {Number(p.views||0).toLocaleString('pt-BR')}</span><span>♡ {Number(p.likes||0).toLocaleString('pt-BR')}</span><span>↻ {Number(p.reposts||0).toLocaleString('pt-BR')}</span><span>◌ {Number(p.comments||0).toLocaleString('pt-BR')}</span><b>◆ {postContribution(p).toLocaleString('pt-BR')} CG</b></div></div><div className="post-card-actions"><button className="icon-btn" onClick={e=>{e.stopPropagation();window.open(p.post_url,'_blank','noopener,noreferrer')}} title="Abrir publicação">↗</button><button className="icon-btn" onClick={e=>{e.stopPropagation();setEdit({...p})}} title="Editar">✎</button><button className="icon-btn" onClick={e=>{e.stopPropagation();remove(p.id)}} title="Excluir">×</button></div></div><Media p={p}/>{expanded===p.id&&<Details p={p}/>}</article>)}{edit&&<div className="modal-backdrop dark"><div className="tracker-modal edit-modal"><div className="modal-head"><div><small>EDIÇÃO</small><strong>Alterar postagem</strong></div><button onClick={()=>setEdit(null)}>×</button></div><div className="modal-body"><label>Título<input value={edit.title||''} onChange={e=>setEdit({...edit,title:e.target.value})}/></label><label>Link<input value={edit.post_url||''} onChange={e=>setEdit({...edit,post_url:e.target.value})}/></label><div className="metric-input-grid"><EditNum label="Visualizações" k="views"/><EditNum label="Curtidas" k="likes"/><EditNum label="Reposts" k="reposts"/><EditNum label="Comentários" k="comments"/></div><label>URL do vídeo<input value={edit.video_url||''} onChange={e=>setEdit({...edit,video_url:e.target.value})}/></label>{edit.video_url&&<VideoPreview url={edit.video_url}/>}</div><div className="modal-actions"><button className="btn" onClick={()=>setEdit(null)}>CANCELAR</button><button className="tracker-add" onClick={save}>SALVAR ALTERAÇÕES</button></div></div></div>}
{expanded&&<div/>} </div>
function EditNum({label,k}:{label:string,k:string}){return <label>{label}<input type="number" min="0" value={edit[k]||0} onChange={e=>setEdit({...edit,[k]:Number(e.target.value)})}/></label>}}
function Media({p}:{p:any}){const imgs=Array.isArray(p.image_urls)?p.image_urls.filter(Boolean):[];if(p.video_url)return <div className="post-media"><VideoPreview url={p.video_url}/></div>;if(!imgs.length)return null;return <div className={`post-media media-grid n${Math.min(imgs.length,4)}`}>{imgs.slice(0,4).map((x:string,i:number)=><img key={i} src={x} alt="Mídia da publicação"/>)}</div>}
function Details({p}:{p:any}){const likes=Number(p.likes||0),special=Number(p.special_reward||0),contrib=postContribution(p);return <div className="post-card-expanded video-details"><div className="details-title"><div><small>RELATÓRIO DA PUBLICAÇÃO</small><h3>Detalhamento da Fórmula Oficial V2</h3></div><strong>◆ {contrib.toLocaleString('pt-BR')} CG</strong></div><div className="post-formula"><div><small>CURTIDAS</small><b>{likes.toLocaleString('pt-BR')}</b></div><div><small>MULTIPLICADOR</small><b>× 2</b></div><div><small>MISSÃO ESPECIAL</small><b>{special.toLocaleString('pt-BR')}</b></div><div><small>CONTRIBUIÇÃO</small><b>{contrib.toLocaleString('pt-BR')}</b></div></div><div className="calculation-box"><p><span>Engajamento elegível</span><b>{likes.toLocaleString('pt-BR')} × 2 = {(likes*2).toLocaleString('pt-BR')}</b></p><p><span>Recompensa da missão</span><b>+ {special.toLocaleString('pt-BR')}</b></p><p className="total"><span>Crystalgin da publicação</span><b>{contrib.toLocaleString('pt-BR')}</b></p></div></div>}
export function VideoPreview({url}:{url:string}){const ref=useRef<HTMLVideoElement>(null);const seek=()=>{const v=ref.current;if(!v)return;try{const max=Math.max(0,(Number.isFinite(v.duration)?v.duration:1.2)-.05);v.currentTime=Math.min(1.2,max);v.pause()}catch{}};return <div className="video-frame"><video ref={ref} src={url} controls playsInline preload="auto" muted onLoadedMetadata={seek} onLoadedData={seek} onSeeked={()=>ref.current?.pause()}/></div>}
