'use client';
import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';
import {supabase} from '@/lib/supabase';
import {formatPostDate} from '@/lib/post-date';
import './add-publication-reference.css';

type ExistingPost={id:string;post_url:string};
const statusId=(url:string)=>url.match(/\/status\/(\d+)/i)?.[1]||'';

export default function ReferencePreviewInjector(){
 const[target,setTarget]=useState<HTMLElement|null>(null),[url,setUrl]=useState(''),[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[duplicate,setDuplicate]=useState<ExistingPost|null>(null);
 useEffect(()=>{let cleanup=()=>{};const bind=()=>{cleanup();const screen=document.querySelector('.add-publication-screen') as HTMLElement|null;if(!screen){setTarget(null);return}screen.classList.add('reference-exact');const input=screen.querySelector('input[placeholder*="x.com"]') as HTMLInputElement|null;if(!input)return;const label=input.closest('label');if(!label)return;let host=screen.querySelector('.x-reference-preview-host') as HTMLElement|null;if(!host){host=document.createElement('div');host.className='x-reference-preview-host';label.insertAdjacentElement('afterend',host)}setTarget(host);setUrl(input.value);const f=()=>setUrl(input.value);input.addEventListener('input',f);cleanup=()=>input.removeEventListener('input',f)};bind();const o=new MutationObserver(bind);o.observe(document.body,{childList:true,subtree:true});return()=>{cleanup();o.disconnect()}},[]);
 useEffect(()=>{if(!/https?:\/\/(?:www\.)?(?:x\.com|twitter\.com)\/[^/]+\/status\/\d+/i.test(url)){setData(null);setDuplicate(null);return}let live=true;const t=setTimeout(async()=>{setLoading(true);try{const [{data:{user}},r]=await Promise.all([supabase.auth.getUser(),fetch('/api/x-metrics',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})})]);const j=await r.json();if(live&&r.ok&&!j.error)setData(j);if(user){const{data:existing}=await supabase.from('posts').select('id,post_url').eq('user_id',user.id);const id=statusId(url);const found=(existing||[]).find((p:any)=>id&&statusId(String(p.post_url||''))===id)||null;if(live)setDuplicate(found)}}catch{if(live)setDuplicate(null)}finally{if(live)setLoading(false)}},300);return()=>{live=false;clearTimeout(t)}},[url]);
 useEffect(()=>{const screen=document.querySelector('.add-publication-screen');const button=screen?.querySelector('.add-submit') as HTMLButtonElement|null;if(!button)return;button.disabled=!!duplicate;button.setAttribute('aria-disabled',duplicate?'true':'false');const guard=(e:Event)=>{if(!duplicate)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation()};button.addEventListener('click',guard,true);return()=>{button.removeEventListener('click',guard,true);if(button.isConnected){button.disabled=false;button.removeAttribute('aria-disabled')}}},[duplicate,target]);
 function showExisting(){const id=statusId(duplicate?.post_url||url);window.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));setTimeout(()=>{const links=Array.from(document.querySelectorAll('a[href]')) as HTMLAnchorElement[];const match=links.find(a=>statusId(a.href)===id);if(match){match.scrollIntoView({behavior:'smooth',block:'center'});const row=match.closest('article,tr,.post-row,.post-card') as HTMLElement|null;row?.classList.add('duplicate-focus');setTimeout(()=>row?.classList.remove('duplicate-focus'),2200)}},180)}
 if(!target)return null;
 return createPortal(<>{duplicate&&<div className="x-duplicate-warning"><span className="x-duplicate-icon">⚠</span><div><strong>Esta publicação já está no seu rastreador.</strong><button type="button" onClick={showExisting}>Ver publicação existente</button></div></div>}{loading&&<div className="x-reference-preview loading">Carregando publicação do X...</div>}{data&&!loading&&<Preview data={data} url={url}/>}</>,target)
}

function Preview({data,url}:{data:any;url:string}){const imgs=(data.image_urls||[]).filter(Boolean),count=imgs.length+(data.video_url?1:0),date=formatPostDate(data.published_at||data.published_date,true);return <div className="x-reference-preview"><div className="x-preview-head">{data.author_avatar?<img className="x-preview-avatar" src={data.author_avatar} alt="Avatar"/>:<div className="x-preview-avatar x-preview-avatar-fallback">𝕏</div>}<div className="x-preview-author"><strong>{data.author_name||data.author_handle}</strong><span>@{data.author_handle}</span></div><div className="x-preview-logo">𝕏</div></div><div className="x-preview-text">{data.title}</div>{count>0&&<div className={`x-preview-media ${count===1?'one':''}`}>{imgs.map((src:string)=><img key={src} src={src} alt="Mídia"/>)}{data.video_url&&<video src={data.video_url} controls playsInline muted/>}</div>}<div className="x-preview-stats"><span>◉ {Number(data.views||0).toLocaleString('pt-BR')}</span><span>◯ {Number(data.comments||0).toLocaleString('pt-BR')}</span><span>↻ {Number(data.reposts||0).toLocaleString('pt-BR')}</span><span className="heart">♥ {Number(data.likes||0).toLocaleString('pt-BR')}</span></div><div className="x-preview-foot"><span>{date}</span><a href={url} target="_blank" rel="noopener noreferrer">Ver no X ↗</a></div></div>}

