'use client';
import {useMemo,useState} from 'react';
import {currentReportPeriod,postDate,postReportCalculation,postsForPeriod,reportMetrics,type ReportPeriod} from '@/lib/report';
import {formatPostDate,POST_TIME_ZONE} from '@/lib/post-date';
import './report-page.css';
import './report-isolation.css';
const number=(value:number)=>Number(value||0).toLocaleString('pt-BR');
const date=(value:Date)=>formatPostDate(value);
export default function ReportPage({posts,profiles,settings,onCancel,period=currentReportPeriod()}:{posts:any[];profiles:any[];settings:any;onCancel:()=>void;period?:ReportPeriod}){const[generatedAt]=useState(()=>new Date());const periodPosts=useMemo(()=>postsForPeriod(posts,period),[posts,period.year,period.month]);const metrics=useMemo(()=>reportMetrics(periodPosts,!!settings?.cap_unlocked),[periodPosts,settings?.cap_unlocked]);const periodLabel=new Intl.DateTimeFormat('pt-BR',{timeZone:POST_TIME_ZONE,month:'long',year:'numeric'}).format(new Date(Date.UTC(period.year,period.month,1,12)));const profile=String(settings?.app_name||settings?.x_handle||'').trim().toUpperCase();return <main className="report-page"><div className="report-controls"><span>Report</span><div className="report-control-actions"><button onClick={onCancel}>Cancelar</button><button className="report-print" onClick={()=>window.print()}>Imprimir ou Salvar PDF</button></div><p>Isso abre o diálogo de impressão. Escolha &apos;Salvar como PDF&apos; no destino.</p></div><div className="report-document"><header className="report-header"><h1>Relatório de Prova de Engajamento</h1><div><section><p><b>Perfil:</b> {profile}</p><p><b>Período:</b> {periodLabel}</p></section><section><p><b>Gerado em:</b> {date(generatedAt)}, {generatedAt.toLocaleTimeString('pt-BR',{timeZone:POST_TIME_ZONE})}</p><p><b>Application:</b> ANONIMOUS_OH Analytics</p></section></div></header><ReportSummary posts={periodPosts.length} views={metrics.views} engagement={metrics.engagement} total={metrics.total}/><PostCalculationLog posts={periodPosts}/><ReportRulesAppendix profiles={profiles} metrics={metrics} capUnlocked={!!settings?.cap_unlocked}/></div></main>}
export function ReportSummary({posts,views,engagement,total}:{posts:number;views:number;engagement:number;total:number}){const cards=[['TOTAL DE POSTS',posts],['TOTAL DE VIEWS',views],['ENGAJAMENTO TOTAL',engagement],['CRYSTGIN TOTAL',total]];return <section className="report-section"><h2>Resumo Mensal</h2><div className="report-summary">{cards.map(([label,value])=><div key={label}><small>{label}</small><strong>{number(Number(value))}</strong></div>)}</div></section>}
export function PostCalculationLog({posts}:{posts:any[]}){const sorted=[...posts].sort((a,b)=>(postDate(a)?.getTime()||0)-(postDate(b)?.getTime()||0));return <section className="report-section report-log"><h2>Log de Cálculo de Posts</h2>{!sorted.length&&<div className="report-empty">Nenhuma publicação encontrada no período atual.</div>}{sorted.map((post,index)=>{const calc=postReportCalculation(post),published=postDate(post);return <article className="report-post" key={post.id||`${post.post_url}-${index}`}><div className="report-post-head"><div className="report-x">𝕏</div><div><h3>{post.mission_name||'Sem missão'}</h3><p>{published?date(published):'Data não informada'}</p></div><a href={post.post_url} target="_blank" rel="noreferrer">{post.post_url||'URL não informada'}</a></div><div className="report-post-metrics"><span>VIEWS <b>{number(post.views)}</b></span><span>CURTIDAS <b>{number(post.likes)}</b></span><span>REPOSTS <b>{number(post.reposts)}</b></span><span>COMENTÁRIOS <b>{number(post.comments)}</b></span></div><div className="report-formula"><p><span>Engajamento (curtidas × 2)</span><b>{number(calc.likes)} × 2 = {number(calc.engagementReward)} CG</b></p><p><span>Missão especial</span><b>+ {number(calc.missionReward)} CG</b></p><p className="report-post-total"><span>Contribuição deste post</span><b>{number(calc.total)} CG</b></p></div></article>})}</section>}
export function ReportRulesAppendix({profiles,metrics,capUnlocked}:{profiles:any[];metrics:ReturnType<typeof reportMetrics>;capUnlocked:boolean}){const active=profiles.filter(profile=>profile.active);return <section className="report-section report-rules"><h2>Apêndice: Regras de Cálculo</h2><div className="report-rules-card"><h3>Fórmula Oficial V2 — configurações ativas</h3><p><span>Recompensa mínima (mínimo de 10 posts)</span><b>+ {number(metrics.base)} CG</b></p><p><span>Bônus de views por faixa do total mensal</span><b>+ {number(metrics.viewsReward)} CG</b></p><p><span>Engajamento</span><b>Curtidas × 2</b></p><p><span>Missões especiais ativas</span><b>+ {number(metrics.special)} CG no período</b></p><p><span>Limite mensal</span><b>{capUnlocked?'Desbloqueado':'30.000 CG'}</b></p>{active.length>0&&<div className="report-active-missions"><h4>Perfis de missão ativos</h4>{active.map(profile=><p key={profile.id}><span><i style={{background:profile.color||'#f6ad55'}}/>{profile.name}</span><b>+ {number(profile.reward)} CG por post</b></p>)}</div>}</div></section>}

