'use client';
import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {supabase} from '@/lib/supabase';
import {monthlyReward,postContribution} from '@/lib/reward';

export default function SiteUpgrades(){
 const[ready,setReady]=useState(false),[uid,setUid]=useState(''),[settings,setSettings]=useState<any>(null),[posts,setPosts]=useState<any[]>([]),[profiles,setProfiles]=useState<any[]>([]),[menu,setMenu]=useState(false),[password,setPassword]=useState(false),[report,setReport]=useState(false),[left,setLeft]=useState(0);
 useEffect(()=>{setReady(true);supabase.auth.getSession().then(async({data})=>{const id=data.session?.user.id||'';setUid(id);if(!id)return;const[{data:s},{data:p},{data:m}]=await Promise.all([supabase.from('user_settings').select('*').eq('user_id',id).maybeSingle(),supabase.from('posts').select('*').eq('user_id',id),supabase.from('mission_profiles').select('*').eq('user_id',id)]);setSettings(s||{});setPosts(p||[]);setProfiles(m||[])})},[]);
 useEffect(()=>{if(!ready)return;const click=(e:MouseEvent)=>{const el=(e.target as HTMLElement).closest('button');if(!el)return;const text=(el.textContent||'').trim().toUpperCase();if(el.classList.contains('user-pill')){e.preventDefault();e.stopImmediatePropagation();setMenu(v=>!v);return}if(text==='CSV'){e.preventDefault();e.stopImmediatePropagation();exportCsv(posts);return}if(text.includes('RELATÓRIO')){e.preventDefault();e.stopImmediatePropagation();setReport(true);return}if(text.includes('ATUALIZAR AGORA'))resetTimer(settings,setLeft)};document.addEventListener('click',click,true);return()=>document.removeEventListener('click',click,true)},[ready,posts,settings]);
 useEffect(()=>{if(!settings?.show_refresh_timer||!Number(settings.refresh_interval)){setLeft(0);return}resetTimer(settings,setLeft);const t=setInterval(()=>setLeft(v=>{if(v<=1){const manual=[...document.querySelectorAll('button')].find(b=>(b.textContent||'').includes('ATUALIZAR AGORA')) as HTMLButtonElement|null;manual?.click();return Math.round(Number(settings.refresh_interval)*3600)}return v-1}),1000);return()=>clearInterval(t)},[settings?.show_refresh_timer,settings?.refresh_interval]);
 useEffect(()=>{const esc=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMenu(false);setPassword(false);setReport(false)}};window.addEventListener('keydown',esc);return()=>window.removeEventListener('keydown',esc)},[]);
 if(!ready)return null;const top=document.querySelector('.exact-topbar');return <>{top&&settings?.show_refresh_timer&&left>0&&createPortal(<div className="auto-timer-pill">↻ <span>PRÓXIMA ATUALIZAÇÃO<br/><b>{fmt(left)}</b></span></div>,top)}{menu&&createPortal(<div className="profile-menu"><button onClick={()=>{setMenu(false);setPassword(true)}}>🔒 Alterar senha</button><button onClick={()=>supabase.auth.signOut()}>↪ Sair</button></div>,document.body)}{password&&createPortal(<Password close={()=>setPassword(false)}/>,document.body)}{report&&createPortal(<Report close={()=>setReport(false)} posts={posts} profiles={profiles} settings={settings}/>,document.body)}</>;
}
function resetTimer(s:any,set:(n:number)=>void){set(Math.max(0,Math.round(Number(s?.refresh_interval||0)*3600)))}
function fmt(s:number){return `${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor((s%3600)/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function exportCsv(posts:any[]){const groups=new Map<string,any[]>();posts.forEach(p=>{const k=p.mission_name||'Sem missão';groups.set(k,[...(groups.get(k)||[]),p])});let out='';[...groups.entries()].sort(([a],[b])=>a.localeCompare(b)).forEach(([mission,rows],i)=>{if(i)out+='\n';out+=`MISSÃO: ${mission}\nData,Link,Visualizações,Curtidas\n`;rows.sort((a,b)=>new Date(a.published_date||a.created_at).getTime()-new Date(b.published_date||b.created_at).getTime()).forEach(p=>{const d=new Date(p.published_date||p.created_at).toLocaleDateString('pt-BR');out+=`"${d}","${String(p.post_url||'').replaceAll('"','""')}",${Number(p.views||0)},${Number(p.likes||0)}\n`})});const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+out],{type:'text/csv;charset=utf-8'}));a.download='publicacoes-por-missao.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function Password({close}:{close:()=>void}){const[p,setP]=useState(''),[c,setC]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);async function go(){if(p.length<8)return setMsg('A senha precisa ter pelo menos 8 caracteres.');if(p!==c)return setMsg('As senhas não são iguais.');setBusy(true);const{error}=await supabase.auth.updateUser({password:p});setBusy(false);setMsg(error?'Não foi possível alterar a senha.':'Senha alterada com sucesso.')}return <div className="upgrade-backdrop"><div className="upgrade-password"><button className="upgrade-x" onClick={close}>×</button><small>SEGURANÇA DA CONTA</small><h2>Alterar senha</h2><label>Nova senha<input type="password" value={p} onChange={e=>setP(e.target.value)}/></label><label>Confirmar nova senha<input type="password" value={c} onChange={e=>setC(e.target.value)}/></label>{msg&&<p>{msg}</p>}<div><button onClick={close}>Cancelar</button><button className="upgrade-primary" disabled={busy} onClick={go}>{busy?'ALTERANDO...':'ALTERAR SENHA'}</button></div></div></div>}
function Report({close,posts,profiles,settings}:{close:()=>void;posts:any[];profiles:any[];settings:any}){const reward=monthlyReward(posts,!!settings?.cap_unlocked),eng=posts.reduce((a,p)=>a+Number(p.likes||0)+Number(p.comments||0)+Number(p.reposts||0),0),now=new Date();const period=now.toLocaleDateString('pt-BR',{month:'long',year:'numeric'});return <div className="report-overlay"><div className="report-toolbar"><h2>Relatório</h2><div><button onClick={close}>Cancelar</button><button className="upgrade-primary" onClick={()=>window.print()}>▣ Salvar PDF</button></div></div><div className="engagement-report"><header><h1>Relatório de Prova de Engajamento</h1><p><b>Perfil:</b> {(settings?.app_name||settings?.x_handle||'VENENO').toUpperCase()}</p><p><b>Período:</b> {period}</p><p><b>Gerado em:</b> {now.toLocaleString('pt-BR')}</p><p><b>Aplicativo:</b> ANONIMOUS_OH Analytics</p></header><h2>Resumo Mensal</h2><div className="report-summary"><div><small>TOTAL DE POSTS</small><b>{posts.length}</b></div><div><small>TOTAL DE VISUALIZAÇÕES</small><b>{reward.views.toLocaleString('pt-BR')}</b></div><div><small>ENGAJAMENTO TOTAL</small><b>{eng.toLocaleString('pt-BR')}</b></div><div><small>CRISTAL TOTAL</small><b>{reward.total.toLocaleString('pt-BR')}</b></div></div><h2>Log de Cálculo de Posts</h2>{[...posts].sort((a,b)=>new Date(a.published_date||a.created_at).getTime()-new Date(b.published_date||b.created_at).getTime()).map((p,i)=><article className="report-post" key={p.id}><h3>Post #{i+1} <span>{p.mission_name||'Sem missão'}</span></h3><p><b>Data:</b> {new Date(p.published_date||p.created_at).toLocaleDateString('pt-BR')}</p><p><b>Link:</b> {p.post_url}</p><div><span>Pontuação Base de Engajamento <b>{Number(p.likes||0)*2} CG</b></span><span>Missão especial <b>+ {Number(p.special_reward||0)} CG</b></span><strong>CRISTAL TOTAL <b>{postContribution(p).toLocaleString('pt-BR')} CG</b></strong></div></article>)}<h2>Apêndice: Norma de Cálculo</h2><section className="report-appendix"><h3>Configurações globais</h3><p>Recompensa básica: <b>800 CG</b> (mínimo 10 postagens)</p><p>Engajamento: <b>curtidas × 2</b></p><p>Limite mensal: <b>{settings?.cap_unlocked?'Desbloqueado':'30.000 CG'}</b></p><h3>Perfis de missão</h3>{profiles.map(p=><p key={p.id}>{p.name}: recompensa <b>{Number(p.reward||0).toLocaleString('pt-BR')} CG</b></p>)}</section></div></div>}
