'use client';
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {Icon,fmt} from './ui-icons';
import './mission-control-v2.css';
export function HistoryPage({uid}:{uid:string}){const[rows,setRows]=useState<any[]>([]);async function load(){const{data}=await supabase.from('archived_periods').select('*').eq('user_id',uid).order('month',{ascending:false});setRows(data||[])}useEffect(()=>{load()},[uid]);async function del(id:number){if(!confirm('Excluir este período arquivado?'))return;await supabase.from('archived_periods').delete().eq('id',id).eq('user_id',uid);load()}return <section className="simple-page"><small>HISTÓRICO</small><h1>Períodos arquivados</h1><p>Registro dos meses fechados e seus cálculos.</p><div className="history-grid">{rows.map(r=><article key={r.id}><small>PERÍODO FECHADO</small><h3>{new Date(r.month+'T12:00:00').toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</h3><strong>◆ {fmt(r.summary?.total||0)}</strong><p>{r.summary?.posts||0} publicações • {fmt(r.summary?.views||0)} visualizações</p><button onClick={()=>del(r.id)}>Excluir período</button></article>)}{!rows.length&&<div className="empty-row">Nenhum período arquivado.</div>}</div></section>}
type RankingMetric='total_views'|'likes'|'crystalgin';
function rankingCycleDate(now=new Date()){const year=now.getFullYear(),month=now.getMonth();const cycle=new Date(year,month+(now.getDate()===1?-1:0),1);return `${cycle.getFullYear()}-${String(cycle.getMonth()+1).padStart(2,'0')}-01`}
const rankingLabels:Record<RankingMetric,string>={total_views:'VISUALIZAÇÕES',likes:'CURTIDAS',crystalgin:'CRYSTGIN'};
export function RankingPage(){
 const[rows,setRows]=useState<any[]>([]),[metric,setMetric]=useState<RankingMetric>('total_views'),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const month=rankingCycleDate();
 useEffect(()=>{let active=true;setLoading(true);setError('');supabase.from('monthly_rankings').select('*').eq('month',month).eq('published',true).limit(100).then(({data,error:loadError})=>{if(!active)return;setRows(data||[]);setError(loadError?'Não foi possível carregar a classificação.':'');setLoading(false)});return()=>{active=false}},[month]);
 const ranked=[...rows].sort((a,b)=>Number(b[metric]||0)-Number(a[metric]||0)||Number(b.likes||0)-Number(a.likes||0)||String(a.x_handle||'').localeCompare(String(b.x_handle||'')));
 const cycleLabel=new Date(`${month}T12:00:00`).toLocaleDateString('pt-BR',{month:'long',year:'numeric'});
 const frozen=new Date().getDate()===1;
 return <section className="simple-page ranking-page"><small>CLASSIFICAÇÃO MENSAL</small><h1>Ranking de desempenho</h1><p>{frozen?'Resultado do ciclo anterior congelado para exibição.':`Ciclo de ${cycleLabel}: contagem do dia 2 até o último dia do mês.`}</p><div className="ranking-tabs" role="group" aria-label="Escolher tipo de ranking">{(Object.keys(rankingLabels) as RankingMetric[]).map(key=><button type="button" key={key} className={metric===key?'active':''} aria-pressed={metric===key} onClick={()=>setMetric(key)}>RANKING DE {rankingLabels[key]}</button>)}</div><div className="rank-table"><div><b aria-label="Posição"></b><b>PARTICIPANTES</b><b>POSTAGENS</b><b>VISUALIZAÇÕES</b><b>CURTIDAS</b><b>CRYSTGIN</b></div>{ranked.map((r,i)=><div key={r.user_id+r.month} className={i<3?'rank-podium':''}><b className={`rank-position rank-position-${i+1}`}>{i+1}</b><span>@{r.x_handle}</span><span>{r.posts_count}</span><span className={metric==='total_views'?'rank-active-value':''}>{fmt(r.total_views)}</span><span className={metric==='likes'?'rank-active-value':''}>{fmt(r.likes)}</span><strong className={metric==='crystalgin'?'rank-active-value':''}>{fmt(r.crystalgin)}</strong></div>)}{loading&&<div className="empty-row">Carregando classificação…</div>}{!loading&&error&&<div className="empty-row">{error}</div>}{!loading&&!error&&!ranked.length&&<div className="empty-row">Nenhum participante neste ciclo.</div>}</div><p className="ranking-rule">No dia 1º, o resultado anterior permanece visível e não recebe novas métricas. Um novo ciclo começa automaticamente no dia 2.</p></section>}
export function ActivityPage({uid}:{uid:string}){const[rows,setRows]=useState<any[]>([]);useEffect(()=>{supabase.from('activity_logs').select('*').eq('user_id',uid).order('created_at',{ascending:false}).limit(100).then(({data})=>setRows(data||[]))},[uid]);return <section className="simple-page"><small>REGISTRO</small><h1>Atividades e notificações</h1><p>Acompanhe alterações importantes da sua conta.</p><div className="activity-list">{rows.map(r=><article key={r.id}><i/><div><b>{r.action}</b><p>{r.description}</p></div><time>{new Date(r.created_at).toLocaleString('pt-BR')}</time></article>)}{!rows.length&&<p>Nenhum registro ainda.</p>}</div></section>}
export function MissionControlPage({uid,reloadProfiles}:{uid:string;reloadProfiles:()=>Promise<void>}){const[rows,setRows]=useState<any[]>([]),[name,setName]=useState(''),[reward,setReward]=useState(0),[color,setColor]=useState('#54c27a'),[description,setDescription]=useState(''),[multiplier,setMultiplier]=useState('1,8'),[limit,setLimit]=useState(0);async function load(){const{data}=await supabase.from('mission_profiles').select('*').eq('user_id',uid).order('active',{ascending:false}).order('name');setRows(data||[])}useEffect(()=>{load()},[uid]);async function create(){if(!name.trim())return;await supabase.from('mission_profiles').insert({user_id:uid,name:name.trim(),network:'X',reward,color,active:true});setName('');setReward(0);setDescription('');setMultiplier('1,8');setLimit(0);await load();await reloadProfiles()}async function toggle(r:any){await supabase.from('mission_profiles').update({active:!r.active}).eq('id',r.id).eq('user_id',uid);await load();await reloadProfiles()}return <section className="mission-control-reference"><div className="mission-control-create"><h2>Adicionar nova missão</h2><div className="mission-create-panel"><label>Nome da missão<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Cores da Missão<div className="mission-color-wrap"><input type="color" value={color} onChange={e=>setColor(e.target.value)}/></div></label><label>Descrição<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4}/></label><label>Multiplicadores de recompensa<div className="mission-multiplier-line"><input value={multiplier} onChange={e=>setMultiplier(e.target.value)}/><button type="button">▱</button></div></label><button className="mission-orange-btn" type="button">Adicionar Multiplicador</button><label>Bônus fixo<input type="number" min="0" value={reward} onChange={e=>setReward(Number(e.target.value))}/></label><label>Limite de envios (0 para ilimitado)<input type="number" min="0" value={limit} onChange={e=>setLimit(Number(e.target.value))}/></label><button className="mission-orange-btn create" onClick={create}><span>＋</span>Criar Missão</button></div></div><div className="mission-control-existing"><h2>Missões existentes</h2><div className="mission-existing-grid">{rows.map(r=><article key={r.id} className="mission-existing-card" style={{'--mission-color':r.color||'#54c27a'} as React.CSSProperties}><div className="mission-existing-main"><h3>{String(r.name||'MISSÃO').toUpperCase()}</h3><p>Engajamento (Curtidas) * 2</p><div className="mission-tags"><span>2X</span><span>{r.active?'ILIMITADO':'ARQUIVADA'}</span></div></div><div className="mission-card-actions"><button onClick={()=>toggle(r)} aria-label="Editar missão">✎</button><button type="button" aria-label="Excluir missão">♲</button></div></article>)}{!rows.length&&<div className="empty-row">Crie sua primeira missão especial.</div>}</div></div></section>}

