alter table public.user_settings
  add column if not exists panel_action_layout text not null default 'classic';

alter table public.user_settings
  drop constraint if exists user_settings_panel_action_layout_check;

alter table public.user_settings
  add constraint user_settings_panel_action_layout_check
  check (panel_action_layout = any (array['classic'::text, 'organized'::text]));

comment on column public.user_settings.panel_action_layout is
  'Chooses the classic or organized panel action layout without changing available actions.';

create table public.tracking_periods (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  start_date date not null,
  end_date date,
  opened_at timestamptz not null default clock_timestamp(),
  closed_at timestamptz,
  archive_id bigint references public.archived_periods(id) on delete set null,
  constraint tracking_period_dates_valid check (end_date is null or end_date >= start_date),
  constraint tracking_period_close_state_valid check (
    (end_date is null and closed_at is null and archive_id is null)
    or (end_date is not null and closed_at is not null)
  )
);

comment on table public.tracking_periods is
  'Explicit per-user tracking periods. Existing posts are never migrated, deleted, or reassigned automatically.';

create unique index tracking_periods_one_open_per_user_idx
  on public.tracking_periods (user_id)
  where end_date is null;

create index tracking_periods_user_opened_idx
  on public.tracking_periods (user_id, opened_at desc);

alter table public.tracking_periods enable row level security;

create policy "tracking periods own select"
on public.tracking_periods
for select
to authenticated
using ((select auth.uid()) = user_id);

revoke all on table public.tracking_periods from public, anon, authenticated;
grant select on table public.tracking_periods to authenticated;

create or replace function public.get_my_active_period()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  active_period public.tracking_periods%rowtype;
  oldest_current_post date;
begin
  if actor is null then
    raise exception 'TRACKING_PERIOD_AUTH_REQUIRED' using errcode = '42501';
  end if;

  select period.*
  into active_period
  from public.tracking_periods period
  where period.user_id = actor
    and period.end_date is null
  order by period.opened_at desc
  limit 1;

  select min(coalesce(
    (post.x_published_at at time zone 'America/Sao_Paulo')::date,
    post.published_at,
    (post.created_at at time zone 'America/Sao_Paulo')::date
  ))
  into oldest_current_post
  from public.posts post
  where post.user_id = actor
    and not post.counting_excluded;

  return jsonb_build_object(
    'id', active_period.id,
    'start_date', active_period.start_date,
    'opened_at', active_period.opened_at,
    'oldest_current_post', oldest_current_post
  );
end;
$$;

create or replace function public.open_my_period(p_start_date date)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  today date := (now() at time zone 'America/Sao_Paulo')::date;
  oldest_current_post date;
  latest_closed_end date;
  opened public.tracking_periods%rowtype;
begin
  if actor is null then
    raise exception 'TRACKING_PERIOD_AUTH_REQUIRED' using errcode = '42501';
  end if;
  if p_start_date is null or p_start_date > today then
    raise exception 'TRACKING_PERIOD_INVALID_START' using errcode = '22007';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(82432, pg_catalog.hashtext(actor::text));

  if exists (
    select 1 from public.tracking_periods period
    where period.user_id = actor and period.end_date is null
  ) then
    raise exception 'TRACKING_PERIOD_ALREADY_OPEN' using errcode = '23505';
  end if;

  select min(coalesce(
    (post.x_published_at at time zone 'America/Sao_Paulo')::date,
    post.published_at,
    (post.created_at at time zone 'America/Sao_Paulo')::date
  ))
  into oldest_current_post
  from public.posts post
  where post.user_id = actor
    and not post.counting_excluded;

  if oldest_current_post is not null and p_start_date > oldest_current_post then
    raise exception 'TRACKING_PERIOD_START_AFTER_CURRENT_POST:%', oldest_current_post using errcode = '22023';
  end if;

  select max(cleanup.period_end)
  into latest_closed_end
  from private.closed_period_post_cleanups cleanup
  where cleanup.user_id = actor
    and cleanup.counting_reopened_at is null;

  if latest_closed_end is not null and p_start_date <= latest_closed_end then
    raise exception 'TRACKING_PERIOD_OVERLAPS_CLOSED:%', latest_closed_end using errcode = '22023';
  end if;

  insert into public.tracking_periods (user_id, start_date)
  values (actor, p_start_date)
  returning * into opened;

  return jsonb_build_object(
    'id', opened.id,
    'start_date', opened.start_date,
    'opened_at', opened.opened_at,
    'oldest_current_post', oldest_current_post
  );
end;
$$;

create or replace function public.close_my_active_period(p_period_end date)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  active_period public.tracking_periods%rowtype;
  archive bigint;
begin
  if actor is null then
    raise exception 'TRACKING_PERIOD_AUTH_REQUIRED' using errcode = '42501';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(82432, pg_catalog.hashtext(actor::text));

  select period.*
  into active_period
  from public.tracking_periods period
  where period.user_id = actor
    and period.end_date is null
  for update;

  if active_period.id is null then
    raise exception 'TRACKING_PERIOD_NOT_OPEN' using errcode = 'P0001';
  end if;

  archive := public.close_period(active_period.start_date, p_period_end);

  update public.tracking_periods period
  set end_date = p_period_end,
      closed_at = clock_timestamp(),
      archive_id = archive
  where period.id = active_period.id
    and period.user_id = actor
    and period.end_date is null;

  return archive;
end;
$$;

create or replace function private.enforce_post_in_open_period()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  period_start date;
  post_date date;
  today date := (now() at time zone 'America/Sao_Paulo')::date;
begin
  if actor is null then
    return new;
  end if;
  if new.user_id <> actor then
    raise exception 'TRACKING_PERIOD_POST_OWNER_MISMATCH' using errcode = '42501';
  end if;

  select period.start_date
  into period_start
  from public.tracking_periods period
  where period.user_id = actor and period.end_date is null
  order by period.opened_at desc
  limit 1;

  if period_start is null then
    raise exception 'TRACKING_PERIOD_REQUIRED' using errcode = 'P0001';
  end if;

  post_date := coalesce(
    (new.x_published_at at time zone 'America/Sao_Paulo')::date,
    new.published_at,
    (new.created_at at time zone 'America/Sao_Paulo')::date,
    today
  );
  if post_date < period_start or post_date > today then
    raise exception 'TRACKING_PERIOD_POST_OUTSIDE:%:%', period_start, today using errcode = '22023';
  end if;
  return new;
end;
$$;

drop trigger if exists enforce_post_in_open_period on public.posts;
create trigger enforce_post_in_open_period
before insert on public.posts
for each row execute function private.enforce_post_in_open_period();

create or replace function public.get_my_x_import_access()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
begin
  if actor is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  return jsonb_build_object(
    'enabled', coalesce((select moderation.x_import_enabled from public.user_moderation moderation where moderation.user_id = actor), false),
    'handle', coalesce((select settings.x_handle from public.user_settings settings where settings.user_id = actor), ''),
    'period_open', exists (
      select 1 from public.tracking_periods period
      where period.user_id = actor and period.end_date is null
    )
  );
end;
$$;

create or replace function public.claim_my_x_import_request()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  handle text;
  period_start date;
  period_id bigint;
  claimed_at timestamptz;
begin
  if actor is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if not coalesce((select moderation.x_import_enabled from public.user_moderation moderation where moderation.user_id = actor), false) then
    raise exception 'X_IMPORT_NOT_ENABLED' using errcode = '42501';
  end if;

  select regexp_replace(trim(settings.x_handle), '^@', '')
  into handle
  from public.user_settings settings
  where settings.user_id = actor;

  if handle is null or handle = '' or handle !~ '^[A-Za-z0-9_]{1,15}$' then
    raise exception 'X_IMPORT_HANDLE_REQUIRED' using errcode = '22023';
  end if;

  select period.id, period.start_date
  into period_id, period_start
  from public.tracking_periods period
  where period.user_id = actor and period.end_date is null
  order by period.opened_at desc
  limit 1;

  if period_id is null then
    raise exception 'X_IMPORT_PERIOD_REQUIRED' using errcode = 'P0001';
  end if;

  insert into private.x_import_rate_limits(user_id, last_requested_at)
  values (actor, clock_timestamp())
  on conflict (user_id) do update
    set last_requested_at = excluded.last_requested_at
    where private.x_import_rate_limits.last_requested_at <= clock_timestamp() - interval '30 seconds'
  returning last_requested_at into claimed_at;

  if claimed_at is null then
    raise exception 'X_IMPORT_RATE_LIMIT' using errcode = 'P0001';
  end if;

  return jsonb_build_object(
    'handle', handle,
    'limit', 100,
    'period_id', period_id,
    'start_date', period_start
  );
end;
$$;

revoke all on function public.get_my_active_period() from public, anon, authenticated;
revoke all on function public.open_my_period(date) from public, anon, authenticated;
revoke all on function public.close_my_active_period(date) from public, anon, authenticated;
revoke all on function public.get_my_x_import_access() from public, anon, authenticated;
revoke all on function public.claim_my_x_import_request() from public, anon, authenticated;
revoke all on function private.enforce_post_in_open_period() from public, anon, authenticated, service_role;

grant execute on function public.get_my_active_period() to authenticated;
grant execute on function public.open_my_period(date) to authenticated;
grant execute on function public.close_my_active_period(date) to authenticated;
grant execute on function public.get_my_x_import_access() to authenticated;
grant execute on function public.claim_my_x_import_request() to authenticated;
