-- Replace the legacy seven-day cooldown with calendar-month closing rules.
-- Early releases are scoped to periods that are already open and are consumed once.

create table if not exists private.period_close_individual_releases (
  id bigint generated by default as identity primary key,
  tracking_period_id bigint not null unique references public.tracking_periods(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  released_at timestamptz not null default clock_timestamp(),
  released_by uuid references auth.users(id) on delete set null,
  reason text not null check (char_length(trim(reason)) between 3 and 500),
  consumed_at timestamptz,
  consumed_period_end date
);

create index if not exists period_close_individual_releases_user_idx
  on private.period_close_individual_releases (user_id, released_at desc);

create table if not exists private.period_close_global_releases (
  id bigint generated by default as identity primary key,
  released_at timestamptz not null default clock_timestamp(),
  released_by uuid references auth.users(id) on delete set null,
  reason text not null check (char_length(trim(reason)) between 3 and 500)
);

create table if not exists private.period_close_global_consumptions (
  release_id bigint not null references private.period_close_global_releases(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  tracking_period_id bigint not null references public.tracking_periods(id) on delete cascade,
  consumed_at timestamptz not null default clock_timestamp(),
  consumed_period_end date not null,
  primary key (release_id, user_id)
);

alter table private.period_close_individual_releases enable row level security;
alter table private.period_close_global_releases enable row level security;
alter table private.period_close_global_consumptions enable row level security;

revoke all on table private.period_close_individual_releases from public, anon, authenticated, service_role;
revoke all on table private.period_close_global_releases from public, anon, authenticated, service_role;
revoke all on table private.period_close_global_consumptions from public, anon, authenticated, service_role;

alter table public.tracking_periods
  add column if not exists corrected_at timestamptz,
  add column if not exists correction_count integer not null default 0;

create index if not exists tracking_periods_archive_id_idx
  on public.tracking_periods (archive_id)
  where archive_id is not null;

create or replace function private.enforce_period_close_cooldown()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
  v_today date := (now() at time zone 'America/Sao_Paulo')::date;
  v_available_on date;
  v_period public.tracking_periods%rowtype;
  v_individual_id bigint;
  v_global_id bigint;
begin
  if v_actor is null or new.user_id <> v_actor then
    raise exception 'ARCHIVED_PERIOD_AUTH_REQUIRED' using errcode = '42501';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(82431, pg_catalog.hashtext(new.user_id::text));

  select period.*
  into v_period
  from public.tracking_periods period
  where period.user_id = new.user_id
    and period.end_date is null
    and period.start_date = new.period_start
  for update;

  if v_period.id is null then
    raise exception 'TRACKING_PERIOD_NOT_OPEN' using errcode = 'P0001';
  end if;

  v_available_on := (date_trunc('month', v_period.opened_at at time zone 'America/Sao_Paulo') + interval '1 month')::date;
  if v_today >= v_available_on then
    return new;
  end if;

  select release.id
  into v_individual_id
  from private.period_close_individual_releases release
  where release.tracking_period_id = v_period.id
    and release.user_id = new.user_id
    and release.consumed_at is null
  for update;

  if v_individual_id is not null then
    update private.period_close_individual_releases
    set consumed_at = clock_timestamp(),
        consumed_period_end = new.period_end
    where id = v_individual_id;
    return new;
  end if;

  select release.id
  into v_global_id
  from private.period_close_global_releases release
  where release.released_at >= v_period.opened_at
    and not exists (
      select 1
      from private.period_close_global_consumptions consumption
      where consumption.release_id = release.id
        and consumption.user_id = new.user_id
    )
  order by release.released_at desc, release.id desc
  limit 1
  for update;

  if v_global_id is not null then
    insert into private.period_close_global_consumptions (
      release_id, user_id, tracking_period_id, consumed_period_end
    ) values (
      v_global_id, new.user_id, v_period.id, new.period_end
    );
    return new;
  end if;

  raise exception 'TRACKING_PERIOD_CLOSE_MONTHLY:%', v_available_on using errcode = 'P0001';
end;
$$;

create or replace function private.record_period_close_cooldown()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_closed_at timestamptz := clock_timestamp();
begin
  -- Retain a compatibility record for older administrative reports, without
  -- granting or enforcing access through this legacy table.
  insert into private.period_close_cooldowns (
    user_id, last_closed_at, next_allowed_at, reset_at, reset_by, updated_at
  ) values (
    new.user_id, v_closed_at, v_closed_at, null, null, v_closed_at
  )
  on conflict (user_id) do update set
    last_closed_at = excluded.last_closed_at,
    next_allowed_at = excluded.next_allowed_at,
    reset_at = null,
    reset_by = null,
    updated_at = excluded.updated_at;
  return new;
end;
$$;

create or replace function public.get_my_active_period()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  active_period public.tracking_periods%rowtype;
  oldest_current_post date;
  available_on date;
  release_source text;
  today date := (now() at time zone 'America/Sao_Paulo')::date;
begin
  if actor is null then
    raise exception 'TRACKING_PERIOD_AUTH_REQUIRED' using errcode = '42501';
  end if;

  select period.*
  into active_period
  from public.tracking_periods period
  where period.user_id = actor and period.end_date is null
  order by period.opened_at desc
  limit 1;

  select min(coalesce(
    (post.x_published_at at time zone 'America/Sao_Paulo')::date,
    post.published_at,
    (post.created_at at time zone 'America/Sao_Paulo')::date
  ))
  into oldest_current_post
  from public.posts post
  where post.user_id = actor and not post.counting_excluded;

  if active_period.id is not null then
    available_on := (date_trunc('month', active_period.opened_at at time zone 'America/Sao_Paulo') + interval '1 month')::date;
    if exists (
      select 1 from private.period_close_individual_releases release
      where release.tracking_period_id = active_period.id
        and release.user_id = actor and release.consumed_at is null
    ) then
      release_source := 'individual';
    elsif exists (
      select 1
      from private.period_close_global_releases release
      where release.released_at >= active_period.opened_at
        and not exists (
          select 1 from private.period_close_global_consumptions consumption
          where consumption.release_id = release.id and consumption.user_id = actor
        )
    ) then
      release_source := 'global';
    end if;
  end if;

  return jsonb_build_object(
    'id', active_period.id,
    'start_date', active_period.start_date,
    'opened_at', active_period.opened_at,
    'oldest_current_post', oldest_current_post,
    'close_available_on', available_on,
    'early_release_source', release_source,
    'can_close', active_period.id is not null and (today >= available_on or release_source is not null)
  );
end;
$$;

create or replace function public.correct_my_active_period_start(p_start_date date)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  today date := (now() at time zone 'America/Sao_Paulo')::date;
  active_period public.tracking_periods%rowtype;
  oldest_current_post date;
  latest_closed_end date;
begin
  if actor is null then
    raise exception 'TRACKING_PERIOD_AUTH_REQUIRED' using errcode = '42501';
  end if;
  if p_start_date is null or p_start_date > today then
    raise exception 'TRACKING_PERIOD_INVALID_START' using errcode = '22007';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(82432, pg_catalog.hashtext(actor::text));

  select period.* into active_period
  from public.tracking_periods period
  where period.user_id = actor and period.end_date is null
  for update;

  if active_period.id is null then
    raise exception 'TRACKING_PERIOD_NOT_OPEN' using errcode = 'P0001';
  end if;

  select min(coalesce(
    (post.x_published_at at time zone 'America/Sao_Paulo')::date,
    post.published_at,
    (post.created_at at time zone 'America/Sao_Paulo')::date
  )) into oldest_current_post
  from public.posts post
  where post.user_id = actor and not post.counting_excluded;

  if oldest_current_post is not null and p_start_date > oldest_current_post then
    raise exception 'TRACKING_PERIOD_START_AFTER_CURRENT_POST:%', oldest_current_post using errcode = '22023';
  end if;

  select max(cleanup.period_end) into latest_closed_end
  from private.closed_period_post_cleanups cleanup
  where cleanup.user_id = actor and cleanup.counting_reopened_at is null;

  if latest_closed_end is not null and p_start_date <= latest_closed_end then
    raise exception 'TRACKING_PERIOD_OVERLAPS_CLOSED:%', latest_closed_end using errcode = '22023';
  end if;

  update public.tracking_periods
  set start_date = p_start_date,
      corrected_at = clock_timestamp(),
      correction_count = correction_count + 1
  where id = active_period.id;

  return public.get_my_active_period();
end;
$$;

create or replace function public.correct_my_closed_period(
  p_archive_id bigint,
  p_period_start date,
  p_period_end date
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  today date := (now() at time zone 'America/Sao_Paulo')::date;
  v_tracking public.tracking_periods%rowtype;
  v_cleanup private.closed_period_post_cleanups%rowtype;
  v_posts jsonb;
  v_posts_count integer;
  v_views bigint;
  v_likes bigint;
  v_reposts bigint;
  v_comments bigint;
  v_special bigint;
  v_base bigint;
  v_views_reward bigint;
  v_engagement_reward bigint;
  v_raw bigint;
  v_limit integer := 30000;
  v_total bigint;
  v_marked integer;
begin
  if actor is null then
    raise exception 'TRACKING_PERIOD_AUTH_REQUIRED' using errcode = '42501';
  end if;
  if p_archive_id is null or p_period_start is null or p_period_end is null
     or p_period_end < p_period_start or p_period_end > today then
    raise exception 'TRACKING_PERIOD_CORRECTION_INVALID_DATES' using errcode = '22007';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(82432, pg_catalog.hashtext(actor::text));
  perform pg_catalog.pg_advisory_xact_lock(82431, pg_catalog.hashtext(actor::text));

  select period.* into v_tracking
  from public.tracking_periods period
  where period.user_id = actor and period.archive_id = p_archive_id and period.end_date is not null
  for update;

  if v_tracking.id is null then
    raise exception 'TRACKING_PERIOD_CORRECTION_NOT_AVAILABLE' using errcode = 'P0001';
  end if;

  select cleanup.* into v_cleanup
  from private.closed_period_post_cleanups cleanup
  where cleanup.archive_id = p_archive_id and cleanup.user_id = actor
  for update;

  if v_cleanup.id is null or v_cleanup.counting_reopened_at is not null or v_cleanup.posts_deleted_at is not null then
    raise exception 'TRACKING_PERIOD_CORRECTION_NOT_AVAILABLE' using errcode = 'P0001';
  end if;

  if exists (
    select 1 from private.closed_period_post_cleanups cleanup
    where cleanup.user_id = actor and cleanup.id <> v_cleanup.id
      and cleanup.counting_reopened_at is null
      and daterange(cleanup.period_start, cleanup.period_end, '[]')
        && daterange(p_period_start, p_period_end, '[]')
  ) or exists (
    select 1 from public.tracking_periods period
    where period.user_id = actor and period.end_date is null
      and period.start_date <= p_period_end
  ) then
    raise exception 'TRACKING_PERIOD_CORRECTION_OVERLAP' using errcode = '22023';
  end if;

  perform set_config('app.closed_period_internal', 'true', true);
  update public.posts post
  set counting_excluded = false, counting_cleanup_id = null
  where post.user_id = actor and post.counting_cleanup_id = v_cleanup.id;

  select
    coalesce(jsonb_agg(to_jsonb(post) order by coalesce(
      (post.x_published_at at time zone 'America/Sao_Paulo')::date,
      post.published_at,
      (post.created_at at time zone 'America/Sao_Paulo')::date
    ), post.id), '[]'::jsonb),
    count(*)::integer,
    coalesce(sum(post.views), 0)::bigint,
    coalesce(sum(post.likes), 0)::bigint,
    coalesce(sum(post.reposts), 0)::bigint,
    coalesce(sum(post.comments), 0)::bigint,
    coalesce(sum(post.special_reward), 0)::bigint
  into v_posts, v_posts_count, v_views, v_likes, v_reposts, v_comments, v_special
  from public.posts post
  where post.user_id = actor and not post.counting_excluded
    and coalesce(
      (post.x_published_at at time zone 'America/Sao_Paulo')::date,
      post.published_at,
      (post.created_at at time zone 'America/Sao_Paulo')::date
    ) between p_period_start and p_period_end;

  if v_posts_count = 0 then
    raise exception 'ARCHIVED_PERIOD_EMPTY' using errcode = 'P0001';
  end if;

  v_base := case when v_posts_count >= 10 then 800 else 0 end;
  v_views_reward := case
    when v_views <= 1000 then 250 when v_views <= 3000 then 750
    when v_views <= 5000 then 1250 when v_views <= 8000 then 2000
    when v_views <= 10000 then 2500 when v_views <= 15000 then 3750
    when v_views <= 20000 then 5000 when v_views <= 25000 then 6250
    when v_views <= 30000 then 7500 else 12500
  end;
  v_engagement_reward := v_likes * 2;
  v_raw := v_base + v_views_reward + v_engagement_reward + v_special;
  select case when settings.cap_unlocked then settings.crystalgin_limit else 30000 end
  into v_limit from public.user_settings settings where settings.user_id = actor;
  v_limit := coalesce(v_limit, 30000);
  v_total := least(v_raw, v_limit);

  update public.archived_periods archive
  set month = date_trunc('month', p_period_start)::date,
      period_start = p_period_start,
      period_end = p_period_end,
      summary = jsonb_build_object(
        'total', v_total, 'total_raw', v_raw, 'crystalgin_limit', v_limit,
        'posts', v_posts_count, 'views', v_views, 'likes', v_likes,
        'reposts', v_reposts, 'comments', v_comments, 'base', v_base,
        'viewsReward', v_views_reward, 'engagementReward', v_engagement_reward,
        'special', v_special
      ),
      posts_snapshot = v_posts
  where archive.id = p_archive_id and archive.user_id = actor;

  update private.closed_period_post_cleanups
  set period_start = p_period_start, period_end = p_period_end, updated_at = clock_timestamp()
  where id = v_cleanup.id;

  update public.posts post
  set counting_excluded = true, counting_cleanup_id = v_cleanup.id
  where post.user_id = actor and not post.counting_excluded
    and coalesce(
      (post.x_published_at at time zone 'America/Sao_Paulo')::date,
      post.published_at,
      (post.created_at at time zone 'America/Sao_Paulo')::date
    ) between p_period_start and p_period_end;
  get diagnostics v_marked = row_count;
  if v_marked <> v_posts_count then
    raise exception 'ARCHIVED_PERIOD_COUNTING_STATE_MISMATCH' using errcode = '40001';
  end if;

  update public.tracking_periods
  set start_date = p_period_start, end_date = p_period_end,
      corrected_at = clock_timestamp(), correction_count = correction_count + 1
  where id = v_tracking.id;

  update public.google_sheets_user_config
  set sheet_month = to_char(date_trunc('month', p_period_end::timestamp) + interval '1 month', 'YYYY-MM'),
      updated_at = now()
  where user_id = actor and enabled and trim(sheet_tab_name) <> '';

  perform private.recalculate_monthly_ranking(actor, now());
  return jsonb_build_object('archive_id', p_archive_id, 'posts', v_posts_count, 'period_start', p_period_start, 'period_end', p_period_end);
exception
  when unique_violation then
    raise exception 'TRACKING_PERIOD_CORRECTION_OVERLAP' using errcode = '23505';
end;
$$;

alter table public.admin_audit_logs drop constraint if exists admin_audit_logs_action_check;
alter table public.admin_audit_logs add constraint admin_audit_logs_action_check check (action = any (array[
  'suspend','reactivate','block_ranking','unblock_ranking',
  'unlock_ranking_control','lock_ranking_control',
  'enable_global_ranking_control','disable_global_ranking_control',
  'disqualify_post','requalify_post','configure_account_cleanup',
  'schedule_account_deletion','cancel_account_deletion','delete_inactive_account',
  'configure_google_sheets','configure_closed_period_post_cleanup',
  'schedule_closed_period_post_cleanup','cancel_closed_period_post_cleanup',
  'delete_closed_period_posts','delete_user_posts_by_date',
  'update_account_access','reopen_closed_period','reset_period_close_cooldown',
  'enable_x_import','disable_x_import',
  'grant_period_close_individual','grant_period_close_global'
]));

create or replace function public.admin_period_close_cooldown_verified(
  p_actor uuid,
  p_action text,
  p_target_user uuid default null,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_period public.tracking_periods%rowtype;
  v_released_at timestamptz;
  v_release_id bigint;
  v_affected integer;
  v_today date := (now() at time zone 'America/Sao_Paulo')::date;
begin
  if not private.is_admin(p_actor) then
    raise exception 'Administrative access required' using errcode = '42501';
  end if;

  if p_action = 'status' then
    return coalesce((
      select jsonb_agg(jsonb_build_object(
        'user_id', period.user_id,
        'last_closed_at', latest.closed_at,
        'next_allowed_at', ((date_trunc('month', period.opened_at at time zone 'America/Sao_Paulo') + interval '1 month') at time zone 'America/Sao_Paulo'),
        'blocked', v_today < (date_trunc('month', period.opened_at at time zone 'America/Sao_Paulo') + interval '1 month')::date
          and individual.released_at is null and global_release.released_at is null,
        'reset_at', coalesce(individual.released_at, global_release.released_at),
        'release_source', case when individual.released_at is not null then 'individual' when global_release.released_at is not null then 'global' end
      ) order by period.opened_at desc)
      from public.tracking_periods period
      left join lateral (
        select max(closed.closed_at) as closed_at
        from public.tracking_periods closed
        where closed.user_id = period.user_id and closed.closed_at is not null
      ) latest on true
      left join lateral (
        select release.released_at
        from private.period_close_individual_releases release
        where release.tracking_period_id = period.id and release.consumed_at is null
        order by release.released_at desc limit 1
      ) individual on true
      left join lateral (
        select release.released_at
        from private.period_close_global_releases release
        where release.released_at >= period.opened_at
          and not exists (
            select 1 from private.period_close_global_consumptions consumption
            where consumption.release_id = release.id and consumption.user_id = period.user_id
          )
        order by release.released_at desc, release.id desc limit 1
      ) global_release on true
      where period.end_date is null
    ), '[]'::jsonb);
  end if;

  if p_action not in ('reset', 'release_all') then
    raise exception 'PERIOD_CLOSE_COOLDOWN_ACTION_INVALID' using errcode = '22023';
  end if;
  if p_reason is null or char_length(trim(p_reason)) < 3 or char_length(trim(p_reason)) > 500 then
    raise exception 'Administrative reason must contain between 3 and 500 characters';
  end if;

  if p_action = 'release_all' then
    select count(*)::integer into v_affected
    from public.tracking_periods period
    where period.end_date is null
      and v_today < (date_trunc('month', period.opened_at at time zone 'America/Sao_Paulo') + interval '1 month')::date
      and not exists (
        select 1 from private.period_close_individual_releases release
        where release.tracking_period_id = period.id and release.consumed_at is null
      )
      and not exists (
        select 1 from private.period_close_global_releases release
        where release.released_at >= period.opened_at
          and not exists (
            select 1 from private.period_close_global_consumptions consumption
            where consumption.release_id = release.id and consumption.user_id = period.user_id
          )
      );
    if v_affected = 0 then
      raise exception 'PERIOD_CLOSE_COOLDOWN_NOT_ACTIVE' using errcode = 'P0001';
    end if;
    insert into private.period_close_global_releases (released_by, reason)
    values (p_actor, trim(p_reason)) returning id, released_at into v_release_id, v_released_at;
    insert into public.admin_audit_logs (admin_user_id, target_user_id, action, reason, metadata)
    values (p_actor, null, 'grant_period_close_global', trim(p_reason), jsonb_build_object(
      'release_id', v_release_id, 'released_at', v_released_at, 'affected_open_periods', v_affected
    ));
    return jsonb_build_object('release_id', v_release_id, 'released_at', v_released_at, 'affected_users', v_affected);
  end if;

  if p_target_user is null or not exists (select 1 from auth.users target where target.id = p_target_user) then
    raise exception 'PERIOD_CLOSE_COOLDOWN_USER_NOT_FOUND' using errcode = 'P0002';
  end if;

  select period.* into v_period
  from public.tracking_periods period
  where period.user_id = p_target_user and period.end_date is null
  for update;

  if v_period.id is null
     or v_today >= (date_trunc('month', v_period.opened_at at time zone 'America/Sao_Paulo') + interval '1 month')::date
     or exists (
       select 1 from private.period_close_individual_releases release
       where release.tracking_period_id = v_period.id and release.consumed_at is null
     )
     or exists (
       select 1 from private.period_close_global_releases release
       where release.released_at >= v_period.opened_at
         and not exists (
           select 1 from private.period_close_global_consumptions consumption
           where consumption.release_id = release.id and consumption.user_id = p_target_user
         )
     ) then
    raise exception 'PERIOD_CLOSE_COOLDOWN_NOT_ACTIVE' using errcode = 'P0001';
  end if;

  insert into private.period_close_individual_releases (tracking_period_id, user_id, released_by, reason)
  values (v_period.id, p_target_user, p_actor, trim(p_reason))
  returning id, released_at into v_release_id, v_released_at;

  insert into public.admin_audit_logs (admin_user_id, target_user_id, action, reason, metadata)
  values (p_actor, p_target_user, 'grant_period_close_individual', trim(p_reason), jsonb_build_object(
    'release_id', v_release_id, 'tracking_period_id', v_period.id,
    'period_start', v_period.start_date, 'released_at', v_released_at
  ));

  return jsonb_build_object('user_id', p_target_user, 'tracking_period_id', v_period.id, 'released_at', v_released_at);
end;
$$;

revoke all on function public.correct_my_active_period_start(date) from public, anon;
grant execute on function public.correct_my_active_period_start(date) to authenticated;
revoke all on function public.correct_my_closed_period(bigint, date, date) from public, anon;
grant execute on function public.correct_my_closed_period(bigint, date, date) to authenticated;
revoke all on function public.admin_period_close_cooldown_verified(uuid, text, uuid, text) from public, anon, authenticated;
grant execute on function public.admin_period_close_cooldown_verified(uuid, text, uuid, text) to service_role;

comment on table private.period_close_individual_releases is 'One-time early close releases bound to one already-open tracking period.';
comment on table private.period_close_global_releases is 'One-time-per-user early close releases for periods open when the release is created.';
comment on function public.correct_my_closed_period(bigint, date, date) is 'Safely corrects an owned tracked archive and atomically rebuilds its snapshot and counting state.';
