-- Configure and execute publication cleanup only for periods that were closed.
-- Cleanup schedules are stored separately so the 40-day archive retention can
-- remain unchanged even when publication retention is longer.

create table if not exists private.closed_period_post_cleanup_settings (
  id smallint primary key default 1 check (id = 1),
  auto_delete_enabled boolean not null default false,
  retention_days integer not null default 40 check (retention_days between 1 and 3650),
  updated_at timestamp with time zone not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

insert into private.closed_period_post_cleanup_settings (id)
values (1)
on conflict (id) do nothing;

create table if not exists private.closed_period_post_cleanups (
  id bigint generated by default as identity primary key,
  archive_id bigint unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  period_start date not null,
  period_end date not null,
  closed_at timestamp with time zone not null,
  retention_days integer check (retention_days between 1 and 3650),
  delete_after timestamp with time zone,
  posts_deleted_at timestamp with time zone,
  posts_deleted_count integer not null default 0 check (posts_deleted_count >= 0),
  delete_source text check (delete_source in ('manual', 'automatic')),
  last_error text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint closed_period_post_cleanups_valid_period check (period_end >= period_start)
);

create index if not exists closed_period_post_cleanups_due_idx
  on private.closed_period_post_cleanups (delete_after)
  where posts_deleted_at is null and delete_after is not null;

create index if not exists closed_period_post_cleanups_user_idx
  on private.closed_period_post_cleanups (user_id, closed_at desc);

revoke all on table private.closed_period_post_cleanup_settings from public, anon, authenticated;
revoke all on table private.closed_period_post_cleanups from public, anon, authenticated;

create or replace function private.capture_closed_period_post_cleanup()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_enabled boolean := false;
  v_days integer := 40;
begin
  select settings.auto_delete_enabled, settings.retention_days
  into v_enabled, v_days
  from private.closed_period_post_cleanup_settings settings
  where settings.id = 1;

  insert into private.closed_period_post_cleanups (
    archive_id,
    user_id,
    period_start,
    period_end,
    closed_at,
    retention_days,
    delete_after
  ) values (
    new.id,
    new.user_id,
    new.period_start,
    new.period_end,
    new.archived_at,
    case when coalesce(v_enabled, false) then coalesce(v_days, 40) else null end,
    case when coalesce(v_enabled, false)
      then new.archived_at + make_interval(days => coalesce(v_days, 40))
      else null
    end
  )
  on conflict (archive_id) do nothing;

  return new;
end;
$$;

drop trigger if exists capture_closed_period_post_cleanup on public.archived_periods;
create trigger capture_closed_period_post_cleanup
after insert on public.archived_periods
for each row execute function private.capture_closed_period_post_cleanup();

insert into private.closed_period_post_cleanups (
  archive_id,
  user_id,
  period_start,
  period_end,
  closed_at
)
select
  archive.id,
  archive.user_id,
  archive.period_start,
  archive.period_end,
  archive.archived_at
from public.archived_periods archive
on conflict (archive_id) do nothing;

create or replace function private.delete_closed_period_posts(
  p_cleanup_id bigint,
  p_source text
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_cleanup private.closed_period_post_cleanups%rowtype;
  v_post_ids bigint[];
  v_deleted integer := 0;
begin
  if p_source not in ('manual', 'automatic') then
    raise exception 'CLOSED_PERIOD_POSTS_INVALID_SOURCE' using errcode = '22023';
  end if;

  select cleanup.*
  into v_cleanup
  from private.closed_period_post_cleanups cleanup
  where cleanup.id = p_cleanup_id
  for update;

  if not found then
    raise exception 'CLOSED_PERIOD_POSTS_NOT_FOUND' using errcode = 'P0002';
  end if;

  if v_cleanup.posts_deleted_at is not null then
    return v_cleanup.posts_deleted_count;
  end if;

  select coalesce(array_agg(post.id order by post.id), '{}'::bigint[])
  into v_post_ids
  from public.posts post
  where post.user_id = v_cleanup.user_id
    and coalesce(
      (post.x_published_at at time zone 'America/Sao_Paulo')::date,
      post.published_at,
      (post.created_at at time zone 'America/Sao_Paulo')::date
    ) between v_cleanup.period_start and v_cleanup.period_end;

  if cardinality(v_post_ids) > 0 then
    update public.admin_audit_logs audit
    set metadata = audit.metadata || jsonb_build_object('deleted_post_id', audit.post_id),
        post_id = null
    where audit.post_id = any(v_post_ids);

    delete from public.posts post
    where post.id = any(v_post_ids);

    get diagnostics v_deleted = row_count;
  end if;

  update private.closed_period_post_cleanups
  set posts_deleted_at = now(),
      posts_deleted_count = v_deleted,
      delete_source = p_source,
      last_error = null,
      updated_at = now()
  where id = p_cleanup_id;

  return v_deleted;
end;
$$;

create or replace function private.delete_due_closed_period_posts()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_cleanup_id bigint;
  v_deleted integer := 0;
begin
  for v_cleanup_id in
    select cleanup.id
    from private.closed_period_post_cleanups cleanup
    where cleanup.posts_deleted_at is null
      and cleanup.delete_after is not null
      and cleanup.delete_after <= now()
    order by cleanup.delete_after, cleanup.id
  loop
    begin
      v_deleted := v_deleted + private.delete_closed_period_posts(v_cleanup_id, 'automatic');
    exception
      when others then
        update private.closed_period_post_cleanups
        set last_error = left(sqlerrm, 500),
            updated_at = now()
        where id = v_cleanup_id;
    end;
  end loop;

  return v_deleted;
end;
$$;

alter table public.admin_audit_logs
  drop constraint if exists admin_audit_logs_action_check;

alter table public.admin_audit_logs
  add constraint admin_audit_logs_action_check check (action = any (array[
    'suspend',
    'reactivate',
    'block_ranking',
    'unblock_ranking',
    'unlock_ranking_control',
    'lock_ranking_control',
    'enable_global_ranking_control',
    'disable_global_ranking_control',
    'disqualify_post',
    'requalify_post',
    'configure_account_cleanup',
    'schedule_account_deletion',
    'cancel_account_deletion',
    'delete_inactive_account',
    'configure_google_sheets',
    'configure_closed_period_post_cleanup',
    'schedule_closed_period_post_cleanup',
    'cancel_closed_period_post_cleanup',
    'delete_closed_period_posts'
  ]));

create or replace function public.admin_set_closed_period_post_cleanup(
  p_enabled boolean,
  p_retention_days integer
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
begin
  if not private.is_admin(v_actor) then
    raise exception 'Administrative access required' using errcode = '42501';
  end if;

  if p_retention_days is null or p_retention_days < 1 or p_retention_days > 3650 then
    raise exception 'CLOSED_PERIOD_POSTS_INVALID_RETENTION' using errcode = '22023';
  end if;

  insert into private.closed_period_post_cleanup_settings (
    id,
    auto_delete_enabled,
    retention_days,
    updated_at,
    updated_by
  ) values (
    1,
    coalesce(p_enabled, false),
    p_retention_days,
    now(),
    v_actor
  )
  on conflict (id) do update
  set auto_delete_enabled = excluded.auto_delete_enabled,
      retention_days = excluded.retention_days,
      updated_at = excluded.updated_at,
      updated_by = excluded.updated_by;

  insert into public.admin_audit_logs (
    admin_user_id,
    action,
    reason,
    metadata
  ) values (
    v_actor,
    'configure_closed_period_post_cleanup',
    case when coalesce(p_enabled, false)
      then 'Exclusão automática de publicações de novos períodos fechados configurada.'
      else 'Exclusão automática de publicações de novos períodos fechados desativada.'
    end,
    jsonb_build_object(
      'enabled', coalesce(p_enabled, false),
      'retention_days', p_retention_days,
      'applies_to', 'future_closed_periods'
    )
  );
end;
$$;

create or replace function public.admin_schedule_closed_period_posts(
  p_cleanup_id bigint,
  p_enabled boolean,
  p_retention_days integer,
  p_reason text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
  v_cleanup private.closed_period_post_cleanups%rowtype;
  v_delete_after timestamp with time zone;
begin
  if not private.is_admin(v_actor) then
    raise exception 'Administrative access required' using errcode = '42501';
  end if;

  if p_reason is null or char_length(trim(p_reason)) < 3 or char_length(trim(p_reason)) > 500 then
    raise exception 'Administrative reason must contain between 3 and 500 characters';
  end if;

  if coalesce(p_enabled, false)
     and (p_retention_days is null or p_retention_days < 1 or p_retention_days > 3650) then
    raise exception 'CLOSED_PERIOD_POSTS_INVALID_RETENTION' using errcode = '22023';
  end if;

  select cleanup.*
  into v_cleanup
  from private.closed_period_post_cleanups cleanup
  where cleanup.id = p_cleanup_id
  for update;

  if not found then
    raise exception 'CLOSED_PERIOD_POSTS_NOT_FOUND' using errcode = 'P0002';
  end if;

  if v_cleanup.posts_deleted_at is not null then
    raise exception 'CLOSED_PERIOD_POSTS_ALREADY_DELETED' using errcode = 'P0001';
  end if;

  v_delete_after := case when coalesce(p_enabled, false)
    then v_cleanup.closed_at + make_interval(days => p_retention_days)
    else null
  end;

  update private.closed_period_post_cleanups
  set retention_days = case when coalesce(p_enabled, false) then p_retention_days else null end,
      delete_after = v_delete_after,
      last_error = null,
      updated_at = now()
  where id = p_cleanup_id;

  insert into public.admin_audit_logs (
    admin_user_id,
    target_user_id,
    action,
    reason,
    metadata
  ) values (
    v_actor,
    v_cleanup.user_id,
    case when coalesce(p_enabled, false)
      then 'schedule_closed_period_post_cleanup'
      else 'cancel_closed_period_post_cleanup'
    end,
    trim(p_reason),
    jsonb_build_object(
      'cleanup_id', p_cleanup_id,
      'period_start', v_cleanup.period_start,
      'period_end', v_cleanup.period_end,
      'retention_days', case when coalesce(p_enabled, false) then p_retention_days else null end,
      'delete_after', v_delete_after
    )
  );
end;
$$;

create or replace function public.admin_delete_closed_period_posts(
  p_cleanup_id bigint,
  p_reason text
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
  v_cleanup private.closed_period_post_cleanups%rowtype;
  v_deleted integer;
begin
  if not private.is_admin(v_actor) then
    raise exception 'Administrative access required' using errcode = '42501';
  end if;

  if p_reason is null or char_length(trim(p_reason)) < 3 or char_length(trim(p_reason)) > 500 then
    raise exception 'Administrative reason must contain between 3 and 500 characters';
  end if;

  select cleanup.*
  into v_cleanup
  from private.closed_period_post_cleanups cleanup
  where cleanup.id = p_cleanup_id;

  if not found then
    raise exception 'CLOSED_PERIOD_POSTS_NOT_FOUND' using errcode = 'P0002';
  end if;

  if v_cleanup.posts_deleted_at is not null then
    raise exception 'CLOSED_PERIOD_POSTS_ALREADY_DELETED' using errcode = 'P0001';
  end if;

  v_deleted := private.delete_closed_period_posts(p_cleanup_id, 'manual');

  insert into public.admin_audit_logs (
    admin_user_id,
    target_user_id,
    action,
    reason,
    metadata
  ) values (
    v_actor,
    v_cleanup.user_id,
    'delete_closed_period_posts',
    trim(p_reason),
    jsonb_build_object(
      'cleanup_id', p_cleanup_id,
      'period_start', v_cleanup.period_start,
      'period_end', v_cleanup.period_end,
      'deleted_posts', v_deleted
    )
  );

  return v_deleted;
end;
$$;

create or replace function public.admin_delete_closed_period_posts_bulk(
  p_cleanup_ids bigint[],
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
  v_cleanup private.closed_period_post_cleanups%rowtype;
  v_deleted integer;
  v_total_deleted integer := 0;
  v_total_periods integer := 0;
  v_unique_count integer;
  v_existing_count integer;
begin
  if not private.is_admin(v_actor) then
    raise exception 'Administrative access required' using errcode = '42501';
  end if;

  if p_reason is null or char_length(trim(p_reason)) < 3 or char_length(trim(p_reason)) > 500 then
    raise exception 'Administrative reason must contain between 3 and 500 characters';
  end if;

  select count(distinct cleanup_id)::integer
  into v_unique_count
  from unnest(p_cleanup_ids) cleanup_id
  where cleanup_id is not null;

  if coalesce(v_unique_count, 0) < 1 or v_unique_count > 100 then
    raise exception 'Select between 1 and 100 closed periods';
  end if;

  select count(*)::integer
  into v_existing_count
  from private.closed_period_post_cleanups cleanup
  where cleanup.id = any(p_cleanup_ids);

  if v_existing_count <> v_unique_count then
    raise exception 'One or more closed periods were not found' using errcode = 'P0002';
  end if;

  for v_cleanup in
    select cleanup.*
    from private.closed_period_post_cleanups cleanup
    where cleanup.id = any(p_cleanup_ids)
      and cleanup.posts_deleted_at is null
    order by cleanup.id
    for update
  loop
    v_deleted := private.delete_closed_period_posts(v_cleanup.id, 'manual');
    v_total_deleted := v_total_deleted + v_deleted;
    v_total_periods := v_total_periods + 1;

    insert into public.admin_audit_logs (
      admin_user_id,
      target_user_id,
      action,
      reason,
      metadata
    ) values (
      v_actor,
      v_cleanup.user_id,
      'delete_closed_period_posts',
      trim(p_reason),
      jsonb_build_object(
        'cleanup_id', v_cleanup.id,
        'period_start', v_cleanup.period_start,
        'period_end', v_cleanup.period_end,
        'deleted_posts', v_deleted,
        'bulk', true
      )
    );
  end loop;

  return jsonb_build_object(
    'periods', v_total_periods,
    'posts', v_total_deleted
  );
end;
$$;

create or replace function public.admin_dashboard()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare actor uuid := auth.uid();
begin
  if not private.is_admin(actor) then
    raise exception 'Administrative access required';
  end if;

  return jsonb_build_object(
    'controls', jsonb_build_object(
      'ranking_self_service_enabled', coalesce((select c.ranking_self_service_enabled from public.app_controls c where c.id = 1), false)
    ),
    'cleanup', coalesce((
      select jsonb_build_object(
        'auto_delete_enabled', s.auto_delete_enabled,
        'inactivity_days', s.inactivity_days,
        'grace_days', s.grace_days,
        'updated_at', s.updated_at
      )
      from public.account_cleanup_settings s
      where s.id = 1
    ), jsonb_build_object('auto_delete_enabled', false, 'inactivity_days', 90, 'grace_days', 7)),
    'post_cleanup', coalesce((
      select jsonb_build_object(
        'auto_delete_enabled', settings.auto_delete_enabled,
        'retention_days', settings.retention_days,
        'updated_at', settings.updated_at
      )
      from private.closed_period_post_cleanup_settings settings
      where settings.id = 1
    ), jsonb_build_object('auto_delete_enabled', false, 'retention_days', 40)),
    'users', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', u.id,
        'email', u.email,
        'username', credentials.username_display,
        'display_name', coalesce(u.raw_user_meta_data->>'display_name',''),
        'profile_name', coalesce(s.app_name,''),
        'created_at', u.created_at,
        'last_sign_in_at', u.last_sign_in_at,
        'last_activity_at', private.account_last_activity(u.id),
        'inactive_days', greatest(0, floor(extract(epoch from (now() - private.account_last_activity(u.id))) / 86400))::integer,
        'x_handle', coalesce(s.x_handle,''),
        'cap_unlocked', coalesce(s.cap_unlocked,false),
        'suspended', coalesce(m.suspended,false),
        'suspension_reason', m.suspension_reason,
        'ranking_blocked', coalesce(m.ranking_blocked,false),
        'ranking_control_unlocked', coalesce(m.ranking_control_unlocked,false),
        'is_admin', (a.user_id is not null),
        'deletion_scheduled_at', q.scheduled_at,
        'deletion_execute_after', q.execute_after,
        'deletion_source', q.source,
        'deletion_last_error', q.last_error
      ) order by u.created_at desc)
      from auth.users u
      left join public.username_credentials credentials on credentials.user_id = u.id
      left join public.user_settings s on s.user_id = u.id
      left join public.user_moderation m on m.user_id = u.id
      left join public.admin_users a on a.user_id = u.id
      left join public.account_deletion_queue q on q.user_id = u.id
    ), '[]'::jsonb),
    'posts', coalesce((
      select jsonb_agg(to_jsonb(p) order by p.published_at desc, p.created_at desc)
      from public.posts p
    ), '[]'::jsonb),
    'periods', coalesce((
      select jsonb_agg(to_jsonb(mp) order by mp.month desc)
      from public.mission_periods mp
    ), '[]'::jsonb),
    'closed_periods', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', cleanup.id,
        'archive_id', cleanup.archive_id,
        'user_id', cleanup.user_id,
        'email', u.email,
        'username', credentials.username_display,
        'display_name', coalesce(u.raw_user_meta_data->>'display_name',''),
        'profile_name', coalesce(settings.app_name,''),
        'period_start', cleanup.period_start,
        'period_end', cleanup.period_end,
        'closed_at', cleanup.closed_at,
        'retention_days', cleanup.retention_days,
        'delete_after', cleanup.delete_after,
        'posts_deleted_at', cleanup.posts_deleted_at,
        'posts_deleted_count', cleanup.posts_deleted_count,
        'delete_source', cleanup.delete_source,
        'last_error', cleanup.last_error,
        'remaining_posts', (
          select count(*)::integer
          from public.posts post
          where post.user_id = cleanup.user_id
            and coalesce(
              (post.x_published_at at time zone 'America/Sao_Paulo')::date,
              post.published_at,
              (post.created_at at time zone 'America/Sao_Paulo')::date
            ) between cleanup.period_start and cleanup.period_end
        )
      ) order by cleanup.closed_at desc, cleanup.id desc)
      from private.closed_period_post_cleanups cleanup
      join auth.users u on u.id = cleanup.user_id
      left join public.username_credentials credentials on credentials.user_id = cleanup.user_id
      left join public.user_settings settings on settings.user_id = cleanup.user_id
    ), '[]'::jsonb),
    'logs', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', l.id,
        'admin_email', admin_user.email,
        'target_email', coalesce(target_user.email, l.metadata->>'target_email'),
        'target_username', coalesce(target_credentials.username_display, l.metadata->>'target_username'),
        'action', l.action,
        'reason', l.reason,
        'post_id', l.post_id,
        'created_at', l.created_at
      ) order by l.created_at desc)
      from public.admin_audit_logs l
      join auth.users admin_user on admin_user.id = l.admin_user_id
      left join auth.users target_user on target_user.id = l.target_user_id
      left join public.username_credentials target_credentials on target_credentials.user_id = l.target_user_id
    ), '[]'::jsonb)
  );
end;
$function$;

revoke all on function private.capture_closed_period_post_cleanup() from public, anon, authenticated;
revoke all on function private.delete_closed_period_posts(bigint, text) from public, anon, authenticated;
revoke all on function private.delete_due_closed_period_posts() from public, anon, authenticated;
grant execute on function private.delete_due_closed_period_posts() to service_role;

revoke all on function public.admin_set_closed_period_post_cleanup(boolean, integer) from public, anon;
revoke all on function public.admin_schedule_closed_period_posts(bigint, boolean, integer, text) from public, anon;
revoke all on function public.admin_delete_closed_period_posts(bigint, text) from public, anon;
revoke all on function public.admin_delete_closed_period_posts_bulk(bigint[], text) from public, anon;
revoke all on function public.admin_dashboard() from public, anon;

grant execute on function public.admin_set_closed_period_post_cleanup(boolean, integer) to authenticated;
grant execute on function public.admin_schedule_closed_period_posts(bigint, boolean, integer, text) to authenticated;
grant execute on function public.admin_delete_closed_period_posts(bigint, text) to authenticated;
grant execute on function public.admin_delete_closed_period_posts_bulk(bigint[], text) to authenticated;
grant execute on function public.admin_dashboard() to authenticated, service_role;

select cron.unschedule(jobid)
from cron.job
where jobname = 'closed-period-posts-cleanup';

select cron.schedule(
  'closed-period-posts-cleanup',
  '45 3 * * *',
  'select private.delete_due_closed_period_posts();'
);

